## Probe: truths, bias and RMSE ranking per cell, unit cost.
source("R/00-model.R")
g <- build_grid(); g$truth <- sapply(seq_len(nrow(g)), function(i) truth(g[i, ]))
set.seed(7); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]
  r <- do.call(rbind, replicate(150, fit_all(draw(cc)), simplify = FALSE)); r$e <- r$est - cc$truth
  a <- aggregate(cbind(bias = e, mse = e^2) ~ method, r, mean); a$rmse <- sqrt(a$mse)
  data.frame(departure = cc$departure, m = cc$m, law = cc$law, truth = round(cc$truth, 3),
             bias = paste(sprintf("%s %.3f", sub("_", " ", a$method), a$bias), collapse = "; "),
             order = paste(a$method[order(a$rmse)], collapse = " < ")) }))
sec <- (proc.time()[["elapsed"]] - t0) / (150 * nrow(g))
md <- c("# DIA-08 probes", "", "Generated by `R/01-probes.R`, 150 replicates per cell. Order is by RMSE, best first.", "",
  "| departure | target mean | law | truth | bias | RMSE order |", "|---|---:|---|---:|---|---|",
  sprintf("| %s | %.1f | %s | %.3f | %s | %s |", rows$departure, rows$m, rows$law, rows$truth, rows$bias, rows$order), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
