## Probe: rank movement across targets and across replicates, five trials per
## comparison, target width 1, 200 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$M == 5 & g$width == 1), function(i) { cc <- g[i, ]; r <- t(replicate(200, one_rep(cc)))
  data.frame(spread = cc$spread, spacing = cc$spacing, across_targets = mean(r[, 1]), true_across = mean(r[, 3]), across_replicates = mean(r[, 2])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(rows))
md <- c("# EST-12 probes", "", "Generated by `R/01-probes.R`. Mean absolute rank change per treatment; five trials per comparison, targets at -1, 0, 1.", "",
  "| modification spread | effect spacing | across targets (estimated) | across targets (true) | across replicates at one target |", "|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %.2f | %.2f | %.2f | %.2f |", rows$spread, rows$spacing, rows$across_targets, rows$true_across, rows$across_replicates), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
