## Probe: mean contrast error by reconstruction in the corners; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(20)
pick <- g[g$n_t == 200 & g$beta == 0.8, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc); r <- t(replicate(300, one_rep(cc, th)))
  data.frame(link = cc$link, skew = cc$skew, summary = cc$summary, t(colMeans(r)),
             rmse_normal = sqrt(mean(r[, "normal"]^2)), rmse_lognormal = sqrt(mean(r[, "lognormal"]^2)),
             rmse_sample = sqrt(mean(r[, "sample_exact"]^2)))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# COV-12 probes", "", "Generated by `R/01-probes.R`. n_T = 200, beta = 0.8, 300 replicates.", "",
  "| link | skew | summary | bias normal | bias lognormal | bias exact sample | RMSE normal | RMSE lognormal | RMSE exact sample |",
  "|---|---:|---|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.1f | %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |", rows$link, rows$skew, rows$summary, rows$normal,
          rows$lognormal, rows$sample_exact, rows$rmse_normal, rows$rmse_lognormal, rows$rmse_sample), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
