## Probe: the three planned SEs against the achieved SD in four cells; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(17)
pick <- g[g$n == 400 & g$prev == 0.1 & g$alloc == "2:1", ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; p <- plan(cc)
  r <- replicate(300, one_rep(cc))
  data.frame(shift = cc$shift, dim = cc$dim, achieved = stats::sd(r, na.rm = TRUE), t(p))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# OVL-06 probes", "", "Generated by `R/01-probes.R`. n = 400, 2:1, prevalence 0.1, 300 replicates.", "",
  "| shift | dim | achieved SD | nominal | Kish ESS | influence |", "|---:|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %d | %.3f | %.3f | %.3f | %.3f |", rows$shift, rows$dim, rows$achieved, rows$se_nominal,
          rows$se_kish, rows$se_influence), "",
  sprintf("Unit cost %.3f s per replicate (plan cost per cell excluded); %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
