## Probe: b* and truth per cell, the two exact controls, unit cost.
source("R/00-model.R")
g <- build_grid(); g$truth <- sapply(seq_len(nrow(g)), function(i) truth(g[i, ])); g$bstar <- sapply(seq_len(nrow(g)), function(i) bstar(g[i, ]))
set.seed(5); t0 <- proc.time()[["elapsed"]]
pr <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { r <- do.call(rbind, replicate(100, one_rep(g[i, ]), simplify = FALSE)); r$cell <- g$cell[i]; r }))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * nrow(g))
pr <- merge(pr, g, by = "cell")
fr <- function(z, m) mean(z[[m]] & z$flip); ff <- function(z, m) mean(!z[[m]] & !z$flip)
s <- do.call(rbind, lapply(split(pr, list(pr$q, pr$width)), function(z) data.frame(q = z$q[1], width = z$width[1],
  excl = mean(!z$covers), flip = mean(z$flip), fr_grid = fr(z, "grid"), ff_grid = ff(z, "grid"), fr_prob = fr(z, "prob"), ff_prob = ff(z, "prob"),
  mc_disagree = mean(z$prob != z$prob_mc), fr_given_incl = mean((z$grid & z$flip)[z$covers]))))
md <- c("# DIA-14 probes", "", "Generated by `R/01-probes.R`, 100 replicates per cell, pooled over cells.", "",
  "| gu | p_t | delta | truth | b* |", "|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %.1f | %.1f | %.3f | %.3f |", g$gu, g$p_t, g$delta, g$truth, g$bstar), "",
  "| q | width | excluded | flip | FR grid | FF grid | FR prob | FF prob | prob MC disagreement | FR grid given included |",
  "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %.2f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f |", s$q, s$width, s$excl, s$flip, s$fr_grid, s$ff_grid, s$fr_prob, s$ff_prob, s$mc_disagree, s$fr_given_incl), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
