## ---------------------------------------------------------------------------
## Probes that must run before the protocol is registered (DESIGN.md section 10).
##
##   Rscript R/03-probes.R
##
## Writes results/probes.rds and results/probes.md. The protocol quotes nothing
## the second file does not contain.
##
## P1  truth and integration order. Both are closed form here, so the probe is a
##     check that the closed form agrees with brute-force Monte Carlo.
## P2  attainability of every requested (rho, CV(T), CV(lambda)) triple.
## P3  interface: does multinma accept arm-specific integration moments, which is
##     what the weighted and borrowed arms need to be package results?
## P4  unit cost per replicate, measured.
## Plus an implementation check: analytic gradient and information against
## numerical derivatives, and the large-sample limit of each method against the
## identity, which is the theorem the weighted arm must attain.
## ---------------------------------------------------------------------------

source("R/02-fit.R")
set.seed(1)
out <- list(); md <- c("# CMP-20 probes", "",
  "Generated by `R/03-probes.R`. Nothing here is typed.", "")

## ---- P1 --------------------------------------------------------------------
g <- build_grid()
cell <- g[g$arm == "main" & g$rho0 == -0.4 & g$drho == 0.4 & g$cv_t == 0.6 &
          g$cv_lam == 0.4 & g$n_arm == 1000, ][1, ]
b <- b_from_cv(cell$cv_lam)
xt <- stats::rnorm(4e6, MEAN_TARGET, SD_X)
mc <- log(mean(exp((b + cell$gamma) * xt + D_B)) / mean(exp(b * xt)))
out$P1 <- c(closed = truth(cell), mc = mc, diff = truth(cell) - mc)
md <- c(md, "## P1: truth", "",
  sprintf("Closed-form target log rate ratio %.6f against a 4,000,000-draw Monte Carlo value %.6f; difference %.2e. The aggregate likelihood's integral is also closed form, so there is no integration order to choose.",
          truth(cell), mc, truth(cell) - mc), "")

## ---- P2 --------------------------------------------------------------------
g$attainable <- vapply(seq_len(nrow(g)), function(i) attainable(g[i, ]), TRUE)
bad <- g[!g$attainable, ]
out$P2 <- list(n_cells = nrow(g), n_attainable = sum(g$attainable), bad = bad)
## Realized factor levels, from the solved laws, so a reader can see the grid
## that actually runs.
lev <- do.call(rbind, lapply(which(g$attainable), function(i) {
  L <- cell_laws(g[i, ])
  data.frame(cell = g$cell[i], cvlamC = L$C$cv_lam, cvlamT = L$T$cv_lam,
             sC = sqrt(L$C$s2), sT = sqrt(L$T$s2),
             pred_bias = predicted_bias(g[i, ]))
}))
out$P2$levels <- lev
md <- c(md, "## P2: attainability", "",
  sprintf("%d of %d cells are attainable by the lognormal-given-covariate exposure law. The %d that are not:",
          sum(g$attainable), nrow(g), nrow(bad)), "",
  if (nrow(bad)) c("| arm | rho0 | drho | CV(T) | CV(lambda) | n |", "|---|---:|---:|---:|---:|---:|",
    sprintf("| %s | %.1f | %.1f | %.1f | %.1f | %d |", bad$arm, bad$rho0, bad$drho,
            bad$cv_t, bad$cv_lam, bad$n_arm)) else "none", "",
  sprintf("Predicted contrast bias over attainable main cells ranges from %.4f to %.4f.",
          min(lev$pred_bias[g$arm[match(lev$cell, g$cell)] == "main"]),
          max(lev$pred_bias[g$arm[match(lev$cell, g$cell)] == "main"])), "")

## ---- implementation check ------------------------------------------------------
d <- draw_network(cell)
m0 <- c(MEAN_AGD, MEAN_AGD); s0 <- c(1, 1)
th <- start_values(d, m0, s0) + stats::rnorm(6, 0, 0.05)
gn <- numDeriv::grad(function(t) -negll(t, d, m0, s0), th)
hn <- numDeriv::hessian(function(t) negll(t, d, m0, s0), th)
ga <- grad_info(th, d, m0, s0)
out$impl <- c(grad = max(abs(gn - ga$g)), info = max(abs(hn - ga$I)) / max(abs(hn)))
md <- c(md, "## Implementation check", "",
  sprintf("Analytic gradient against numerical: largest absolute difference %.2e. Analytic observed information against numerical Hessian: largest relative difference %.2e.",
          out$impl[["grad"]], out$impl[["info"]]), "")

## Replicated check at 1000 per arm: each method's mean error against its
## prediction (zero for weighted and borrowed, the identity for unweighted), and
## model SE against empirical SD.
set.seed(5)
rr <- replicate(200, { d <- draw_network(cell); f <- fit_all(d); th <- truth(cell)
  sapply(f[c("unweighted", "weighted", "borrowed")], function(x)
    c(err = x$est - th, se = x$se, cov = abs(x$est - th) < 1.96 * x$se)) }, simplify = "array")
lim <- do.call(rbind, lapply(dimnames(rr)[[2]], function(m) data.frame(
  method = m, bias = mean(rr["err", m, ]), mcse = stats::sd(rr["err", m, ]) / sqrt(200),
  emp_sd = stats::sd(rr["err", m, ]), mod_se = mean(rr["se", m, ]), cover = mean(rr["cov", m, ]))))
out$limit <- lim
md <- c(md, sprintf("## Replicated check (200 replicates, 1000 per arm, predicted unweighted bias %.4f)", predicted_bias(cell)), "",
  "| method | bias | MCSE | empirical SD | model SE | coverage |", "|---|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.4f | %.4f | %.4f | %.4f | %.3f |", lim$method, lim$bias, lim$mcse,
          lim$emp_sd, lim$mod_se, lim$cover), "")

## ---- P3 --------------------------------------------------------------------
p3 <- tryCatch({
  suppressPackageStartupMessages(library(multinma))
  ipd <- data.frame(studyc = "S1", trtc = rep(c("C", "A"), each = 50),
                    y = stats::rpois(100, 1), T = 1, x1 = stats::rnorm(100))
  agd <- data.frame(studyc = "S2", trtc = c("C", "B"), r = c(40, 30), E = c(50, 50),
                    x1_mean = c(0.5, 0.9), x1_sd = c(1, 1))
  net <- combine_network(
    set_ipd(ipd, study = studyc, trt = trtc, r = y, E = T),
    set_agd_arm(agd, study = studyc, trt = trtc, r = r, E = E), trt_ref = "C")
  ## The covariate is not called x: add_integration() dispatches on an
  ## argument of that name.
  net <- add_integration(net, x1 = distr(qnorm, mean = x1_mean, sd = x1_sd), n_int = 64)
  pts <- net$agd_arm$.int_x1
  mC <- mean(pts[[1]]); mB <- mean(pts[[2]])
  list(ok = TRUE, mean_C = mC, mean_B = mB,
       version = as.character(utils::packageVersion("multinma")))
}, error = function(e) list(ok = FALSE, msg = conditionMessage(e)))
out$P3 <- p3
md <- c(md, "## P3: interface", "",
  if (isTRUE(p3$ok)) sprintf("multinma %s accepts arm-specific integration moments: supplied means 0.5 and 0.9 give integration points with means %.3f and %.3f in the two arms. The weighted and borrowed arms are therefore expressible as package inputs, by passing exposure-weighted moments to `add_integration()`; this study fits its own implementation of the same likelihood for speed.",
    p3$version, p3$mean_C, p3$mean_B) else paste("Interface check failed:", p3$msg), "")

## ---- P4 --------------------------------------------------------------------
tm <- vapply(c(250L, 1000L), function(n) {
  cc <- cell; cc$n_arm <- n
  t0 <- proc.time()[["elapsed"]]
  for (r in 1:40) fit_all(draw_network(cc))
  (proc.time()[["elapsed"]] - t0) / 40
}, 0)
n_main <- sum(g$attainable)
cost_h <- n_main * N_SIM * mean(tm) / 3600
out$P4 <- c(sec_250 = tm[1], sec_1000 = tm[2], cells = n_main, n_sim = N_SIM,
            core_hours = cost_h)
md <- c(md, "## P4: unit cost", "",
  sprintf("Measured per replicate, all methods: %.3f s at 250 per arm and %.3f s at 1000 per arm, single core, on a shared machine. %d attainable cells at %d replicates is %.1f core-hours at the mean of the two.",
          tm[1], tm[2], n_main, N_SIM, cost_h), "")

saveRDS(out, "results/probes.rds")
writeLines(md, "results/probes.md")
cat(md, sep = "\n")
