## Probe: coverage by rule in two cells (100 replicates), unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(14)
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$n == 300), function(i) {
  cc <- g[i, ]; th <- truth(cc)
  r <- do.call(rbind, lapply(1:100, function(k) fit_all(cc, draw(cc))))
  do.call(rbind, lapply(split(r, r$rule), function(z) data.frame(n = cc$n, n_mod = cc$n_mod, rule = z$rule[1],
    bias = mean(z$est - th), emp_sd = stats::sd(z$est), mean_se = mean(z$se),
    cover = mean(abs(z$est - th) <= 1.96 * z$se), mean_sel = mean(z$n_sel), hit = mean(z$hit))))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * 2)
md <- c("# DEC-11 probes", "", "Generated by `R/01-probes.R`. 300 per arm, 100 replicates.", "",
  "| true modifiers | rule | bias | empirical SD | mean SE | coverage | mean selected | all true selected |",
  "|---:|---|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %s | %.4f | %.3f | %.3f | %.3f | %.2f | %.2f |", rows$n_mod, rows$rule, rows$bias, rows$emp_sd,
          rows$mean_se, rows$cover, rows$mean_sel, rows$hit), "",
  sprintf("Unit cost %.2f s per replicate at 300 per arm; %d cells at %d replicates is roughly %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
