## P1 exact truths, G-computation limit bias and unsupported mass under the true law
## and the independence reconstruction; P2 smoke replicates, the rho = 0 identity
## and unit cost. Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); g <- build_grid(); out <- c("# Probes", "", "Generated by `R/01-probes.R`.", "")
g$truth <- vapply(seq_len(nrow(g)), function(i) truth(g[i, ]), 0)
g$lim_bias <- -g$h * hinge_mean(2 * g$mu, 2 + 2 * g$rho)
g$mass_true <- unsupported_mass(g$mu, g$rho); g$mass_indep <- unsupported_mass(g$mu, 0)
g$mass_env <- vapply(g$mu, function(m) max(unsupported_mass(m, ENV_RHO)), 0)
out <- c(out, "## P1 exact (population level)", "",
  "Unsupported mass is P(x1 + x2 > 2) under the target law; the independence reconstruction reports the rho = 0 value in every cell.", "",
  "| cell | target mean | true rho | shape | truth | G-comp limit bias | unsupported mass, true law | independence | envelope |",
  "|---:|---:|---:|---|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.1f | %.1f | %s | %.3f | %.3f | %.3f | %.3f | %.3f |", g$cell, g$mu, g$rho, g$shape, g$truth, g$lim_bias, g$mass_true, g$mass_indep, g$mass_env), "")

## P2 smoke: 3 replicates in four cells; the rho = 0 cells must give identical
## true-law and independence diagnostics (same law, common random numbers).
sm <- g[g$cell %in% c(3, 4, 9, 12), ]; t0 <- proc.time()
s <- do.call(rbind, lapply(seq_len(nrow(sm)), function(i) do.call(rbind, lapply(1:3, function(k) {
  set.seed(MASTER_SEED %% 1e6 + 7919L * k + 104729L * sm$cell[i]); transform(one_rep(sm[i, ]), cell = sm$cell[i], rep = k) }))))
tt <- proc.time() - t0; cpu <- (tt[["user.self"]] + tt[["sys.self"]]) / (3 * nrow(sm))
s <- merge(s, g[, c("cell", "truth", "lim_bias", "mass_true", "mass_indep")], by = "cell")
e <- unique(s[, c("cell", "rep", "est", "se", "truth", "lim_bias")])
h <- s[s$diag == "hull", ]
out <- c(out, "## P2 smoke (3 replicates per cell)", "",
  "| cell | rep | error | limit bias | SE | hull mass, true law | independence |", "|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %d | %.3f | %.3f | %.3f | %.3f | %.3f |", h$cell, h$rep, h$est - h$truth, h$lim_bias, h$se, h$true_law, h$indep), "",
  sprintf("- rho = 0 cells: largest |true-law minus independence| over all diagnostics %.1e (must be 0)", max(abs(s$true_law - s$indep)[s$cell %in% g$cell[g$rho == 0]])),
  sprintf("- mean diagnostics over the smoke, true law: %s", paste(sprintf("%s %.3f", DIAGS, tapply(s$true_law, s$diag, mean)[DIAGS]), collapse = ", ")),
  sprintf("- CPU per replicate %.2f s (elapsed %.2f s) on a shared machine at load above 500", cpu, tt[["elapsed"]] / (3 * nrow(sm))),
  sprintf("- registered run: %d cells x %d replicates, about %.2f CPU-hours", nrow(g), N_SIM, nrow(g) * N_SIM * cpu / 3600), "")
## P3 predicted primary: cell-level AUROC over the bent cells, failure probability
## from the limit bias and the smoke SE by target mean, diagnostic at its exact value.
b <- g[g$shape == "bent", ]; sem <- tapply(e$se, g$mu[match(e$cell, g$cell)], mean)
b$pf <- stats::pnorm(-1.96 + abs(b$lim_bias) / sem[as.character(b$mu)]) + stats::pnorm(-1.96 - abs(b$lim_bias) / sem[as.character(b$mu)])
cauc <- function(dv) { W <- outer(b$pf, 1 - b$pf); S <- outer(dv, dv, function(a, c) ifelse(abs(a - c) < 1e-9, 0.5, as.numeric(a > c))); sum(W * S) / sum(W) }
pa <- c(hull_true = cauc(b$mass_true), hull_indep = cauc(b$mass_indep), extrap_true = cauc(hinge_mean(2 * b$mu, 2 + 2 * b$rho)), extrap_indep = cauc(hinge_mean(2 * b$mu, 2)))
out <- c(out, "## P3 predicted primary (cell-level approximation, bent cells)", "",
  sprintf("- failure probability by cell %s: %s", paste(b$cell, collapse = ", "), paste(sprintf("%.3f", b$pf), collapse = ", ")),
  sprintf("- AUROC, hull mass: true law %.3f, independence %.3f, gap %.3f", pa[["hull_true"]], pa[["hull_indep"]], pa[["hull_true"]] - pa[["hull_indep"]]),
  sprintf("- AUROC, extrapolated modification: true law %.3f, independence %.3f, gap %.3f", pa[["extrap_true"]], pa[["extrap_indep"]], pa[["extrap_true"]] - pa[["extrap_indep"]]), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
