## Probe: bias of each estimator against truth and against Delta*, unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(4); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]
  r <- t(replicate(200, fit_all(cc, draw(cc))))
  data.frame(gamma = cc$gamma, imbalance = cc$imbalance, mu1_t = cc$mu1_t, t(round(colMeans(r[, 1:8]) - truth(cc), 3)), ess = round(mean(r[, 9]), 3)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(g))
md <- c("# QBA-11 probes", "", "Generated by `R/01-probes.R`. Bias against the truth, 200 replicates per cell.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(rows, 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
