## Probe: check alarm rate and contrast bias in the 2 x 2 corners; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(18)
pick <- g[g$n_t == 200 & g$mu_u %in% c(0, 0.6) & g$mu_v %in% c(0, 0.6), ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; tr <- truths(cc)
  r <- t(replicate(300, fit(draw(cc))))
  data.frame(mu_u = cc$mu_u, mu_v = cc$mu_v, bias = mean(r[, "est"]) - tr[["log_or_BA"]],
             cover = mean(abs(r[, "est"] - tr[["log_or_BA"]]) <= 1.96 * r[, "se"]),
             alarm = mean(abs(r[, "check_z"]) > 1.96))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# IDN-10 probes", "", "Generated by `R/01-probes.R`. Target 200 per arm, 300 replicates.", "",
  "| prognostic shift u | modifier shift v | contrast bias | coverage | check alarm rate (abs z > 1.96) |",
  "|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %.1f | %.4f | %.3f | %.3f |", rows$mu_u, rows$mu_v, rows$bias, rows$cover, rows$alarm), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
