## Probe: coverage with and without propagation at small arms; infeasibility rate;
## unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(10)
pick <- g[g$eps == 1 & g$release == "means", ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]
  r <- do.call(rbind, lapply(1:200, function(k) { s <- draw_source(cc); tm <- draw_target_moments(cc)
    f <- fit_all(cc, s, tm); f$truth <- truth(cc, tm); f }))
  do.call(rbind, lapply(split(r, r$method), function(z) data.frame(n_t = cc$n_t, em = cc$em, method = z$method[1],
    infeasible = mean(!z$ok), bias = mean(z$est - z$truth), cover = mean(abs(z$est - z$truth) <= 1.96 * z$se),
    emp_sd = stats::sd(z$est - z$truth), mean_se = mean(z$se))))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(pick))
md <- c("# ADJ-15 probes", "", "Generated by `R/01-probes.R`. epsilon 1, means released, 200 replicates.", "",
  "| target n | modification | method | infeasible | bias | coverage | SD of error | mean SE |", "|---:|---|---|---:|---:|---:|---:|---:|",
  sprintf("| %d | %s | %s | %.3f | %.4f | %.3f | %.3f | %.3f |", rows$n_t, rows$em, rows$method, rows$infeasible,
          rows$bias, rows$cover, rows$emp_sd, rows$mean_se), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
