## Probes: P1 truths and analytic terms per cell; one replicate per cell in every
## method, timed; null and positive controls on 20 replicates; one multinma smoke
## fit (2 chains, 200 iterations each), timed. Writes results/probes.md.
source("R/00-model.R"); g <- build_grid()
out <- c("# MOD-09 probes", "", sprintf("Generated by `R/01-probes.R`; multinma %s, rstan %s.", utils::packageVersion("multinma"), utils::packageVersion("rstan")), "")
tr <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) data.frame(g[i, ], t(truth(g[i, ])))))
mc_err <- local({ t9 <- truth(g[1, ]); body(truth) <- parse(text = sub("set.seed(9)", "set.seed(10)", paste(deparse(body(truth)), collapse = "\n"), fixed = TRUE))[[1]]; abs(truth(g[1, ])[["truth"]] - t9[["truth"]]) })
out <- c(out, "## P1 truth and analytic terms", "", "| cell | gap | overlap | information | modification | truth | gap term (MAIC and STC) | aggregation term |", "|---:|---|---|---|---|---:|---:|---:|",
  sprintf("| %d | %s | %s | %s | %s | %.4f | %.4f | %.4f |", tr$cell, tr$gap, tr$overlap, tr$info, tr$em, tr$truth, tr$gap_bias, tr$aggregation_bias), "",
  sprintf("Monte Carlo error of the truth: two seeds differ by %.4f (cell 1).", mc_err), "")

t0 <- proc.time()[["user.self"]]
one <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { set.seed(50 + i); z <- one_rep(g[i, ]); z$cell <- i; z }))
sec <- (proc.time()[["user.self"]] - t0) / nrow(g)
out <- c(out, "## One replicate per cell", "", sprintf("Failed fits: %d of %d; ML-NMR optimizer non-convergence: %d. Mean CPU s per fit: %s.", sum(!is.na(one$error)), nrow(one),
  sum(one$converged[one$method == "mlnmr"] == 0), paste(sprintf("%s %.3f", c("maic", "stc", "mlnmr"), tapply(one$sec, one$method, mean)[c("maic", "stc", "mlnmr")]), collapse = ", ")), "")

ctrl <- function(cid, k = 20) { z <- do.call(rbind, lapply(1:k, function(r) { set.seed(MASTER_SEED %% 1e6 + 7919L * r + 104729L * 99L + cid); one_rep(g[cid, ]) }))
  z$e <- z$est - tr$truth[cid]; z }
nc <- ctrl(which(g$em == "none")); pc <- ctrl(which(g$gap == "high" & g$overlap == "poor" & g$info == "joint" & g$em == "shared"))
sm <- function(z, lab) sprintf("- %s, %s: bias %.3f (MCSE %.3f), coverage %.2f, RMSE %.3f, mean SE %.3f, empirical SD %.3f.", lab, c("maic", "stc", "mlnmr"),
  tapply(z$e, z$method, mean)[c("maic", "stc", "mlnmr")], (tapply(z$e, z$method, stats::sd) / sqrt(20))[c("maic", "stc", "mlnmr")],
  tapply(abs(z$e) <= 1.96 * z$se, z$method, mean)[c("maic", "stc", "mlnmr")], sqrt(tapply(z$e^2, z$method, mean))[c("maic", "stc", "mlnmr")],
  tapply(z$se, z$method, mean)[c("maic", "stc", "mlnmr")], tapply(z$est, z$method, stats::sd)[c("maic", "stc", "mlnmr")])
out <- c(out, "## Controls, 20 replicates", "", sm(nc, "null"), sm(pc, "positive"), "")

set.seed(3); t1 <- proc.time()
b <- tryCatch(burden_rep(g[1, ], seed = 3L, chains = 2L, iter = 200L), error = function(e) conditionMessage(e)); el <- proc.time() - t1
set.seed(3); ml <- one_rep(g[1, ]); ml <- ml[ml$method == "mlnmr", ]
cpu <- el[["user.self"]] + el[["sys.self"]]; ext <- cpu * (2 * 2000) / (2 * 200)
out <- c(out, "## multinma smoke fit (cell 1, 2 chains, 200 iterations each)", "",
  if (is.character(b)) paste("- failed:", b) else c(sprintf("- B vs C in the target: posterior mean %.3f (SD %.3f); maximum likelihood on the same data %.3f (SE %.3f).", b$est, b$sd, ml$est, ml$se),
    sprintf("- divergent %d, refit %s, max Rhat %.3f, warnings %d.", as.integer(b$divergent), b$refit, b$max_rhat, as.integer(b$n_warnings))),
  sprintf("- %.1f CPU s (%.1f s elapsed); extrapolated to 2 chains x 2000 iterations: %.0f CPU s per fit (linear in iterations, one fit at about 13%% CPU share).", cpu, el[["elapsed"]], ext),
  sprintf("- Registered run: main grid %d cells x %d x %.2f CPU s = %.1f CPU hours; burden %d cells x %d fits x %.0f CPU s = %.1f CPU hours (more if refits occur).",
    nrow(g), N_SIM, sec, nrow(g) * N_SIM * sec / 3600, nrow(g), N_BURDEN, ext, nrow(g) * N_BURDEN * ext / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
