#!/usr/bin/env python3
"""Check a response letter against what the manuscript actually says.

This program has now published a response describing a change the manuscript did
not contain five times across five studies. The failures have taken three shapes,
and this file has one guard for each.

  1. The change was never made.            -> POSITIVE list.
  2. The change was made in one place and  -> NEGATIVE list: the retracted text
     the old claim survived elsewhere.        must be ABSENT, not merely
                                              contradicted somewhere else.
  3. The pattern matched nothing because   -> flat(): whitespace is collapsed
     the paragraph had been re-wrapped.       before matching, so reflowed prose
                                              still matches.

Study 5 added a fourth shape, which no text check can catch: a number in a
hand-written summary that disagreed with the analysis that produced it. The fix
for that is not a better checker, it is `R/08-decision.R`, which generates the
summary from the result files so there is no transcription step to get wrong.
This file therefore also asserts that the generated document is newer than the
results it claims to summarise.

  python3 review/verify-response.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)


def flat(s):
    return re.sub(r"\s+", " ", s)


def read(*p):
    return flat(open(os.path.join(STUDY, *p), encoding="utf8").read())


QMD = read("manuscript", "manuscript.qmd")
MD = read("out", "IDN-05.md")
PROTO = read("protocol.md")
DEC = read("results", "decision.md")
ANALYSIS = read("R", "05-analyze.R")
FIT = read("R", "02-fit.R")

# study.json feeds the catalog page, and until round two it was the one published
# artifact nothing checked. It still carried the title retracted in revision one,
# together with three claims the manuscript had already withdrawn. Same failure,
# new file. It is covered here now.
STUDY_JSON = read("study.json")

POSITIVE = [
    # 1. our formalizations, not one published rule
    ("formalization disclosed, source", QMD, "is not one procedure"),
    ("formalization disclosed, rendered", MD, "five explicit rules of our own construction"),
    ("same point in the limitations", QMD, "not a uniquely defined published rule"),
    # 2. the prior drives the margin and equivalence rules
    ("prior arithmetic present", QMD, "places `r pc(2 * (1 - pnorm(EPS / (sqrt(2) * PRIOR_REG_SD))), 3)`"),
    ("prior arithmetic rendered", MD, "above the 0.95 threshold at which the margin rule fires"),
    ("reframed as precision", MD, "within a factor of three"),
    ("the precision actually needed", QMD, r"\varepsilon / 1.96 ="),
    # 3. M1 is algebraic and displacement is not the only axis
    ("M1 labelled algebraic", MD, "algebraic identity rather than an empirical finding"),
    ("M1 qualified", MD, "on the drift, and the check is blind to both"),
    # 4. the eligibility amendment
    ("amendment in the protocol", PROTO, "That rule was amended before the reported run"),
    ("departure disclosed in the paper", QMD, "A departure from the registered eligibility rule"),
    ("clean-subset comparison computed", ANALYSIS, "strategy-paired-clean"),
    ("clean-subset comparison reported", MD, "in which **all four** fits met their convergence"),
    # 5. the estimand under heterogeneity
    ("estimand caveat", QMD, "The estimand under treatment-effect heterogeneity"),
    ("oracle does not remove it", MD, "the oracle is also a fixed-effect"),
    # 6. Monte Carlo error
    ("pooled power computed", ANALYSIS, '"power-pooled"'),
    ("pooled power table", MD, "pooled across all eight design strata"),
    ("per-cell SE stated where it matters", MD, "is not an upper bound on anything"),
    ("M4 downgraded", MD, "M4 is reported as not clearly met"),
    ("M4 downgraded in the decision record", DEC, "not clearly met"),
    ("strategy comparison paired", ANALYSIS, "strategy-paired"),
    ("paired intervals reported", MD, "the comparison is paired"),
    # 7. integration instability
    ("instability not called small", MD, "A first draft called this small; it is not"),
    ("integration subset described", MD, "which is the configuration where quadrature is"),
    # 8. the decision document is generated
    ("decision generated by script", DEC, "computed by `R/08-decision.R`"),
    ("script exists", os.path.exists(os.path.join(STUDY, "R", "08-decision.R")), True),
    ("M2 count corrected", DEC, "5 of 8"),
    # 9. the boundary is not the boundary
    ("boundary correction", MD, "These cells sit just *below* the boundary, not on it"),
    ("boundary correction in the decision record", DEC, "just BELOW the material"),
    # 10. the calibration logic error
    ("target-aware calibration reported", MD, "Adding the displacement as a second predictor"),
    ("logic error retracted", MD, "That is a logical error: a predictor can improve a"),
    # 11. the derived quantity cannot carry a title
    ("instability of the derived quantity", MD, "Those should agree and do not"),
    ("nothing rests on it", MD, "no headline claim in this paper rests on it"),
    ("title replaced", QMD, "raises the shared effect modifier check's alarm rate"),
    # 12. the recommendation
    ("exchangeable omission conceded", MD, "Package non-implementation is a reason for its absence, not a justification"),

    # ---- round two -----------------------------------------------------------
    # R2.1 the blanks that shipped to three reviewers
    ("render guard exists", os.path.exists(os.path.join(HERE, "verify-render.py")), True),
    ("amendment rate renders", MD, "the rate is 0.020"),
    ("lookup fails loudly instead of rendering nothing", QMD, "power-pooled has %d rows at drift"),
    ("amendment arm pooled into the same table", ANALYSIS, '"amendment" else "registered"'),
    # R2.2 the contraction denominator bug
    ("prior passed into check_stats", FIT, "prior_sd = PRIOR_REG_SD)"),
    ("contraction divided by the prior used", FIT, "1 - apply(g, 2, sd) / prior_sd"),
    ("repair applied to stored fits", ANALYSIS, "fix_contraction"),
    ("direction corrected in the paper", MD, "contraction on the drifting covariate **falls**"),
    ("recorded in the protocol", PROTO, "Contraction was computed by dividing"),
    # R2.3 the weighted bound
    ("weighted interval implemented", ANALYSIS, "weighted_upper <- function"),
    ("weighted bound reported", DEC, "The primary bound was computed for the wrong quantity"),
    ("both bounds visible", MD, "which is the Wilson bound on the **unweighted** risk"),
    # R2.4 the undisclosed protocol departure
    ("departure in the protocol", PROTO, "This arm ran at **30 replicates"),
    ("departure in the paper", MD, "is a departure from registration and was not previously"),
    ("accounting computed, not derived", ANALYSIS, '"prior-sensitivity-accounting"'),
    # R2.5 the AUROC that was computed and dropped
    ("auroc pooled by drift", ANALYSIS, '"auroc-vs-drift-pooled"'),
    ("auroc reported", MD, "Ranking networks with a violation above networks without one"),
    ("omission disclosed", MD, "omitted from the first two drafts"),
    ("omission recorded in the protocol", PROTO, "omitted from the first two drafts"),
    # R2.6 the nominal-coverage claim
    ("coverage claim replaced", MD, "Avoiding selection is necessary for coverage, not sufficient"),
    ("split by heterogeneity computed", ANALYSIS, '"type1-by-heterogeneity"'),
    # R2.7 the calibration explanation, third attempt
    ("held-out discrimination computed", ANALYSIS, "auc_knows_shift = wauc"),
    ("correct explanation given", MD, "calibration in the large"),
    ("stronger claim drawn", MD, "Knowing the target is worth far more than knowing the"),
    # R2.8 denominators
    ("m3 carries both poolings", ANALYSIS, '"drifting covariate only"'),
    ("m3 pooling stated", MD, "the pooling the table above displays"),
    ("m4 clustered by replicate", ANALYSIS, "se_clustered"),
    ("null denominator corrected", PROTO, "800 observations"),
    # R2.9 the strategy claim, scoped
    ("weighted paired comparison", ANALYSIS, "w_abs_diff = wx[1]"),
    ("indistinguishable at zero", MD, "indistinguishable at 0"),
    ("weighting mismatch disclosed", MD, "computed **unweighted** while the RMSE table beside them"),
    # R2.10 the worst diagnostic
    ("worst across any model computed", ANALYSIS, '"sampler-worst-overall"'),
    ("worst across any model reported", MD, "are the worst reached by the fully relaxed model"),
    # R2.11 citations
    ("exact package build cited", read("manuscript", "references.bib"), "8489bd83f388f3cb48062947cd9ab083218947dd"),
    ("dic cutoffs marked as ours", MD, "read at cutoffs of our choosing"),
    ("decision curve cited", MD, "net benefit ([7]"),
    ("novelty claim scoped", MD, "not a claim about treatment-by-covariate"),
    # R2.12 the catalog record
    ("study.json title updated", STUDY_JSON, "raises the shared effect modifier check's alarm rate"),
    ("study.json records the departure", STUDY_JSON, "against the 100 registered"),
]

NEGATIVE = [
    ("the withdrawn title", QMD, "to between two and twelve times the difference"),
    ("the same, rendered", MD, "to between two and twelve times the difference"),
    ("'at most eight analyses in a hundred'", MD, "at most eight analyses in a hundred"),
    ("'M4 is confirmed'", MD, "**M4 is confirmed**"),
    ("the unqualified all-clear claim", MD, "It cannot return an all-clear"),
    ("'the violation that exactly matters'", MD, "This is the violation that exactly matters"),
    # The retracted phrase legitimately survives inside the sentence that
    # retracts it, so the pattern targets the ASSERTION, not the words. The
    # positive list carries the matching requirement that the retraction is
    # present, so this pair cannot both pass while the claim still stands.
    ("the boundary claim, asserted", MD,
     "violation that precisely changes a decision, the check is silent"),
    ("'small beside the resolution problem'", MD, "small beside the resolution problem"),
    ("the calibration logic error", MD, "because displacement does not enter the statistic at all"),
    ("'One number explains the rest'", QMD, "One number explains the rest"),
    ("'depends entirely on how far the target sits'", MD, "depends entirely on how far the target sits"),
    ("the hand-typed M2 count", DEC, "6 of 8"),

    # ---- round two -----------------------------------------------------------
    ("the unweighted bound presented as the gate", DEC, "Upper bound 0.777"),
    ("the inverted contraction direction", MD, "to 0.68--0.70 under"),
    ("the false nominal-coverage claim", MD, "the credible interval keeps its nominal coverage"),
    ("'at every displacement'", MD, "lowest error of the three strategies at every displacement"),
    ("the unqualified lower-bound claim", MD,
     "the failures reported here are therefore lower bounds on the failures in practice"),
    ("the stale null denominator", PROTO, "720 observations"),
    ("'the only thing that determines the harm'", QMD, "blind to the only thing"),
    ("the second wrong calibration explanation", MD,
     "so displacement carries no information the mapping did not already have. What fails"),
    ("the withdrawn title in the catalog record", STUDY_JSON,
     "to between two and twelve times the difference"),
    ("the retracted prior-free claim in the catalog record", STUDY_JSON,
     "One number carries the paper and it is free of the prior"),
    ("the retracted lower-bound claim in the catalog record", STUDY_JSON,
     "so these failures are lower bounds"),
    ("the superseded verdict bound in the catalog record", STUDY_JSON, "is 0.777"),
]


def main():
    bad = 0
    print("must be present:")
    for name, hay, needle in POSITIVE:
        ok = (hay is True or hay == needle) if isinstance(hay, bool) \
            else flat(needle) in hay
        bad += not ok
        print(f"  {'ok     ' if ok else 'MISSING'}  {name}")
    print("\nmust be gone:")
    for name, hay, needle in NEGATIVE:
        ok = flat(needle) not in hay
        bad += not ok
        print(f"  {'ok     ' if ok else 'PRESENT'}  {name}")

    print("\nthe generated summary is not stale:")
    dec = os.path.getmtime(os.path.join(STUDY, "results", "decision.md"))
    stale = [f for f in os.listdir(os.path.join(STUDY, "results"))
             if f.endswith(".csv") and
             os.path.getmtime(os.path.join(STUDY, "results", f)) > dec]
    ok = not stale
    bad += not ok
    print(f"  {'ok     ' if ok else 'STALE  '}  decision.md vs results/*.csv"
          + (f" ({len(stale)} newer)" if stale else ""))

    n = len(POSITIVE) + len(NEGATIVE) + 1
    print(f"\n{n - bad} of {n} pass")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
