## Probe: bias of the naive and source-IPCW contrasts, prevalence 0.2, 100 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
pick <- g[g$prev == 0.2, ]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) { cc <- pick[i, ]; r <- t(replicate(100, fit_all(cc, draw(cc))))
  data.frame(design = cc$design, alpha_s = cc$alpha_s, alpha_t = cc$alpha_t, truth = truth(cc), bias_naive = mean(r[, "naive"]) - truth(cc),
             bias_ipcw = mean(r[, "ipcw"]) - truth(cc), fragile = mean(r[, "fragile"]), delta_true = stats::median(r[, "delta_true"], na.rm = TRUE)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * nrow(pick))
md <- c("# OUT-07 probes", "", "Generated by `R/01-probes.R`. Censoring prevalence 0.2, 100 replicates; RMST at 24 months.", "",
  "| design | alpha source | alpha comparator | truth | bias naive | bias source IPCW | fragile over delta 0.5 to 2 | median delta reproducing truth |",
  "|---|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %d | %d | %.3f | %.3f | %.3f | %.2f | %.2f |", rows$design, rows$alpha_s, rows$alpha_t, rows$truth, rows$bias_naive, rows$bias_ipcw, rows$fragile, rows$delta_true), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
