## Probe: truths, bias and coverage of the CIF difference and of A's CIF, cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
pick <- g[g$b == 0, ]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) { cc <- pick[i, ]; th <- truth(cc)
  r <- t(replicate(100, fit_all(draw(cc))))
  f <- function(m, t) c(mean(r[, m] - t, na.rm = TRUE), mean(abs(r[, m] - t) <= 1.96 * r[, paste0(m, "_se")], na.rm = TRUE))
  b <- sapply(c("maic", "stc", "stc_recal"), function(m) f(m, th[["cif_diff"]])[1])
  a <- sapply(c("maic_A", "stc_A", "stc_recal_A"), function(m) f(m, th[["cif_A"]]))
  data.frame(k_t = cc$k_t, m_t = cc$m_t, truth_diff = th[["cif_diff"]], truth_A = th[["cif_A"]],
             bias_diff_maic = b[1], bias_diff_stc = b[2], bias_diff_recal = b[3],
             bias_A_maic = a[1, 1], bias_A_stc = a[1, 2], bias_A_recal = a[1, 3],
             cov_A_maic = a[2, 1], cov_A_stc = a[2, 2], cov_A_recal = a[2, 3]) }))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * nrow(pick))
md <- c("# DIA-09 probes", "", "Generated by `R/01-probes.R`. No modification, 100 replicates. Bias of the CIF difference, then bias and coverage of A's CIF.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
