## Probes: the population ratio EESS / (ESS p) by direction, the relation of EESS
## to the sandwich variance, failure rates, unit cost. Writes results/probes.md.
source("R/00-model.R")
g <- build_grid(); set.seed(2)
pick <- g[g$risk == 0.02 & g$shift == 0.9 & g$n == 1000 & g$delta == -0.5, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; a <- alpha_for(cc); th <- truth(cc)
  r <- t(replicate(200, one_rep(cc, a)))
  ok <- r[, "ok"] == 1
  data.frame(direction = cc$direction,
             ratio_pop = median(r[, "eess_pop"] / r[, "essp_pop"]),
             eess_x_var = median((r[ok, "eess"] * r[ok, "se"]^2)),
             fail = mean(!ok),
             cover = mean(abs(r[ok, "est"] - th) < 1.96 * r[ok, "se"]),
             bias = mean(r[ok, "est"] - th))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(pick))
md <- c("# OUT-02 probes", "", "Generated by `R/01-probes.R`. Risk 0.02, shift 0.9, 1000 per arm, delta -0.5, 200 replicates.", "",
  "| direction | median EESS/(ESS p), true risks | median EESS x sandwich variance | no estimate | coverage | bias |",
  "|---|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.3f | %.3f | %.3f | %.3f | %.4f |", rows$direction, rows$ratio_pop, rows$eess_x_var,
          rows$fail, rows$cover, rows$bias), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
