## Probe: failure share, ESS and coverage along the grid, 100 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1)
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- do.call(rbind, replicate(100, fit_all(cc, draw(cc)), simplify = FALSE))
  do.call(rbind, lapply(split(r, r$m), function(z) data.frame(n = cc$n, m = z$m[1], original_feasible = mean(z$orig_ok), resample_failure = mean(z$fail_share),
    ess = mean(z$ess, na.rm = TRUE), coverage_given_success = mean(z$lo <= z$m & z$m <= z$hi, na.rm = TRUE),
    coverage_unconditional = mean(ifelse(is.na(z$lo), FALSE, z$lo <= z$m & z$m <= z$hi))))) }))
md <- c("# QBA-23 probes", "", "Generated by `R/01-probes.R`, 100 replicates, 200 bootstrap resamples. A first version of the weight solver overflowed and was replaced by a log-sum-exp minimization before this probe.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "")
writeLines(md, "results/probes.md")
