## Probe: unadjusted and adjusted node-split flag rates, four studies per comparison,
## modification 0.4, 300 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$M == 4 & g$beta == 0.4), function(i) { cc <- g[i, ]; r <- t(replicate(300, fit_all(cc, draw(cc))))
  data.frame(gap = cc$gap, iota = cc$iota, w = mean(r[, "w"]), flag_unadj = mean(r[, "p_unadj"] < ALPHA), iota_adj = mean(r[, "iota_adj"]),
             se_adj = mean(r[, "se_adj"]), flag_adj = mean(r[, "p_adj"] < ALPHA)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(rows))
md <- c("# HET-04 probes", "", "Generated by `R/01-probes.R`. Four studies per comparison, modification 0.4, 300 replicates.", "",
  "| covariate gap | true inconsistency | mean unadjusted w | unadjusted flag | mean adjusted estimate | its SE | adjusted flag |", "|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %+.1f | %.3f | %.3f | %.3f | %.3f | %.3f |", rows$gap, rows$iota, rows$w, rows$flag_unadj, rows$iota_adj, rows$se_adj, rows$flag_adj), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
