## Probe: bias, coverage and screen detection by mechanism, M = 5, V = 0.2; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$M == 5 & (g$V == 0.2 | g$mech == "none")), function(i) { cc <- g[i, ]
  r <- t(replicate(400, fit_all(cc, draw(cc)))); tr <- truth(cc); f <- function(p) mean(r[, p] < ALPHA)
  data.frame(mech = cc$mech, V = cc$V, bias = mean(r[, "est"]) - tr, coverage = mean(abs(r[, "est"] - tr) <= 1.96 * r[, "se"]),
             dissim = f("p_dissim"), incons = f("p_incons"), het = f("p_het"),
             any = mean(r[, "p_dissim"] < ALPHA | r[, "p_incons"] < ALPHA | r[, "p_het"] < ALPHA)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (400 * nrow(rows))
md <- c("# IDN-01 probes", "", "Generated by `R/01-probes.R`. Five studies per comparison, violation 0.2, 400 replicates.", "",
  "| mechanism | V | bias | coverage | dissimilarity | inconsistency | heterogeneity | any screen |", "|---|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.1f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f |", rows$mech, rows$V, rows$bias, rows$coverage, rows$dissim, rows$incons, rows$het, rows$any), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
