## P1 truths and the collapsibility gap; P2 exact least-false STC bias and asymptotic
## SDs of MAIC and STC, hence predicted onsets; P3 smoke replicates of every method
## and unit cost. Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); g <- build_grid(); out <- c("# Probes", "", "Generated by `R/01-probes.R`.", "")
Ew <- function(f, mu) sum(GH$weights * f(mu + GH$nodes))          # E f(x), x ~ N(mu, 1)

## Least-false per-arm model on the source population (x ~ N(0, 1)): logistic or
## linear regression of the true mean on (1, x), solved exactly on the quadrature nodes.
lf <- function(cell, a) { m <- mean_resp(GH$nodes, a, cell)
  f <- suppressWarnings(stats::glm(m ~ GH$nodes, weights = GH$weights, family = if (cell$scale == "binary") stats::quasibinomial() else stats::gaussian()))
  unname(stats::coef(f)) }

asym <- function(cell) {
  delta <- sqrt(cell$d2); bin <- cell$scale == "binary"; inv <- if (bin) stats::plogis else identity
  v <- function(x, a) if (bin) { p <- mean_resp(x, a, cell); p * (1 - p) } else rep(1, length(x))
  mT <- vapply(0:1, function(a) Ew(function(x) mean_resp(x, a, cell), delta), 0)
  dl <- function(m) if (bin) 1 / (m * (1 - m)) else 1
  ## MAIC with the tilt estimated: influence w (y - mT - c (x - delta)), c = Cov_T(m, x).
  vm <- sum(vapply(0:1, function(a) { cc <- Ew(function(x) (mean_resp(x, a, cell) - mT[a + 1]) * (x - delta), delta)
    exp(cell$d2) * Ew(function(x) v(x, a) + (mean_resp(x, a, cell) - mT[a + 1] - cc * (x - delta))^2, 2 * delta) * dl(mT[a + 1])^2 / N_ARM }, 0))
  ## STC: sandwich variance of each arm's least-false fit, delta method to the contrast.
  lim <- numeric(2); vs <- 0
  for (a in 0:1) { b <- lf(cell, a); X <- cbind(1, GH$nodes); lp <- drop(X %*% b)
    vt <- if (bin) stats::dlogis(lp) else rep(1, length(lp))
    Br <- crossprod(X * GH$weights * vt, X); M <- crossprod(X * GH$weights * (v(GH$nodes, a) + (mean_resp(GH$nodes, a, cell) - inv(lp))^2), X)
    Va <- solve(Br) %*% M %*% solve(Br) / N_ARM
    Xt <- cbind(1, delta + GH$nodes); lpt <- drop(Xt %*% b); ma <- sum(GH$weights * inv(lpt))
    ga <- colSums(GH$weights * (if (bin) stats::dlogis(lpt) else 1) * Xt) * dl(ma)
    lim[a + 1] <- ma; vs <- vs + drop(t(ga) %*% Va %*% ga) }
  c(truth = truth(cell), stc_bias = link_contrast(lim[2], lim[1], cell$scale) - truth(cell), sd_maic = sqrt(vm), sd_stc = sqrt(vs),
    cond_at_mean = TAU0 + TAU1 * delta + cell$beta2 * (cell$d2 - 1))
}
p <- cbind(g, t(vapply(seq_len(nrow(g)), function(i) asym(g[i, ]), numeric(5))))
p$gap <- p$cond_at_mean - p$truth
ref <- p[p$level == 1, c("curvature", "scale", "sd_maic", "sd_stc")]; names(ref)[3:4] <- c("sd0_maic", "sd0_stc")
p <- merge(p, ref, by = c("curvature", "scale")); p <- p[order(p$cell), ]
pred <- do.call(rbind, lapply(split(p, list(p$scale, p$curvature), drop = TRUE), function(z) { z <- z[order(z$d2), ]
  data.frame(scale = z$scale[1], curvature = z$curvature[1], maic_var = onset(z$d2, z$sd_maic / z$sd0_maic, SD_RATIO),
             stc_bias = onset(z$d2, abs(z$stc_bias), MATERIAL), stc_var = onset(z$d2, z$sd_stc / z$sd0_stc, SD_RATIO)) }))
out <- c(out, "## P1, P2 truths, exact STC limit bias, asymptotic SDs (per cell)", "",
  "Collapsibility gap: the conditional effect at the target mean minus the marginal truth; every method here targets the marginal estimand, so it does not enter any error.", "",
  "| cell | scale | curvature | log(1+chi2) | truth | STC limit bias | SD MAIC | SD STC | SD ratio MAIC | SD ratio STC | gap |",
  "|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %s | %s | %.1f | %.3f | %.3f | %.3f | %.3f | %.2f | %.2f | %.3f |", p$cell, p$scale, p$curvature, p$d2, p$truth, p$stc_bias,
          p$sd_maic, p$sd_stc, p$sd_maic / p$sd0_maic, p$sd_stc / p$sd0_stc, p$gap), "",
  sprintf("## Predicted onsets in log(1 + chi^2) (interpolated; %.1f = not reached on the grid)", BEYOND), "",
  "| scale | curvature | MAIC variance onset | STC bias onset | STC variance onset |", "|---|---|---:|---:|---:|",
  sprintf("| %s | %s | %.2f | %.2f | %.2f |", pred$scale, pred$curvature, pred$maic_var, pred$stc_bias, pred$stc_var), "")

## P3 smoke: every method in the extreme cells, 3 replicates each, and unit cost.
sm <- g[g$cell %in% c(1, 18, 19, 24, 34, 36), ]
t0 <- proc.time()
s <- do.call(rbind, lapply(seq_len(nrow(sm)), function(i) do.call(rbind, lapply(1:3, function(k) {
  set.seed(MASTER_SEED %% 1e6 + 7919L * k + 104729L * crn_block(sm[i, ]))
  transform(one_rep(sm[i, ]), cell = sm$cell[i], truth = truth(sm[i, ]), rep = k) }))))
tt <- proc.time() - t0; cpu <- (tt[["user.self"]] + tt[["sys.self"]]) / (3 * nrow(sm))
s$err <- s$est - s$truth
agg <- aggregate(cbind(err, se, ess) ~ cell + method, data = transform(s, se = ifelse(is.na(se), -1, se), ess = ifelse(is.na(ess), -1, ess)), FUN = mean, na.action = na.pass)
out <- c(out, "## P3 smoke (3 replicates per cell; mean error, -1 where a method has no SE)", "",
  "| cell | method | mean error | mean SE | mean ESS |", "|---:|---|---:|---:|---:|",
  sprintf("| %d | %s | %.3f | %.3f | %.1f |", agg$cell, agg$method, agg$err, agg$se, agg$ess), "",
  sprintf("- missing estimates: %d of %d", sum(is.na(s$est)), nrow(s)),
  sprintf("- CPU per replicate %.2f s (elapsed %.2f s) on a shared machine at load above 500", cpu, tt[["elapsed"]] / (3 * nrow(sm))),
  sprintf("- registered run: %d cells x %d replicates, about %.1f CPU-hours", nrow(g), N_SIM, nrow(g) * N_SIM * cpu / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
