## ---------------------------------------------------------------------------
## Probes before registration. Writes results/probes.rds and results/probes.md.
##
##   Rscript R/02-probes.R
##
## P1  exact truth by quadrature against brute-force Monte Carlo.
## P2  realizability: every cell is a normal law, so every (strength, ratio,
##     shift) triple exists; what P2 reports instead is the population-level
##     bias each cell implies, which is what the grid can show at all.
## P3  inference for the index-variance arm, and a pilot of every arm at the
##     cells that decide the primary outcome.
## P4  unit cost.
## ---------------------------------------------------------------------------

source("R/01-model.R")
set.seed(3)
out <- list()
md <- c("# COV-03 probes", "", "Generated by `R/02-probes.R`.", "")
g <- build_grid()

## ---- P1 -----------------------------------------------------------------------
cell <- g[g$design == "anchored" & g$var_T == 4 & g$ratio == 2 & g$shift == 0.6 &
          g$em == "present", ][1, ]
gg <- gcoef(cell$var_T); N <- 2e6
x <- matrix(stats::rnorm(N * P, cell$shift, 1), N, P)
eta0 <- ALPHA + gg * rowSums(x)
mc <- (stats::qlogis(mean(stats::plogis(eta0 + DELTA_B))) - stats::qlogis(mean(stats::plogis(eta0)))) -
      (stats::qlogis(mean(stats::plogis(eta0 + DELTA_A + EM_BETA * x[, 1]))) - stats::qlogis(mean(stats::plogis(eta0))))
rm(x)
out$P1 <- c(quad = truth(cell), mc = mc)
md <- c(md, "## P1: truth", "",
  sprintf("Quadrature %.5f against 2,000,000-draw Monte Carlo %.5f at the most extreme cell (difference %.1e).",
          truth(cell), mc, truth(cell) - mc), "")

## ---- P2 -----------------------------------------------------------------------
g$bucher_bias <- vapply(seq_len(nrow(g)), function(i) bucher_bias(g[i, ]), 0)
g$naive_bias <- vapply(seq_len(nrow(g)), function(i) unanchored_naive_bias(g[i, ]), 0)
g$second_order <- vapply(seq_len(nrow(g)), function(i) second_order_bias(g[i, ]), 0)
a <- g[g$design == "anchored" & g$em == "none", ]
out$P2 <- a
md <- c(md, "## P2: population-level bias of the unadjusted anchored comparison, no modification", "",
  "Delta_A(T) - Delta_A(S), exact, with the second-order approximation beside it.", "",
  "| Var_T(u) | ratio | shift | exact | second order |", "|---:|---:|---:|---:|---:|",
  sprintf("| %.2f | %.1f | %.1f | %.4f | %.4f |", a$var_T, a$ratio, a$shift, a$bucher_bias, a$second_order), "",
  sprintf("With ratio 1 and a nonzero shift the exact bias is %.4f to %.4f: the index mean moves the marginal log OR, contrary to DESIGN.md section 2.",
          min(a$bucher_bias[a$ratio == 1 & a$shift > 0]), max(a$bucher_bias[a$ratio == 1 & a$shift > 0])), "")

## ---- P3 and pilot ----------------------------------------------------------------
pilot_cells <- g[g$design == "anchored" & g$em == "none" & g$var_T == 4 & g$shift == 0.3, ]
pl <- do.call(rbind, lapply(seq_len(nrow(pilot_cells)), function(i) {
  cc <- pilot_cells[i, ]; th <- truth(cc)
  r <- lapply(1:150, function(k) fit_all(cc, draw(cc)))
  do.call(rbind, lapply(names(r[[1]]), function(m) {
    v <- do.call(rbind, lapply(r, function(z) z[[m]]))
    e <- v[, "est"] - th
    data.frame(ratio = cc$ratio, method = m, bias = mean(e), mcse = stats::sd(e) / sqrt(nrow(v)),
               emp_sd = stats::sd(e), mod_se = mean(v[, "se"]),
               cover = mean(abs(e) < 1.96 * v[, "se"]), ess = mean(v[, "ess"]))
  }))
}))
out$pilot <- pl
md <- c(md, "## P3: pilot at Var_T(u) = 4, shift 0.3, anchored, no modification (150 replicates)", "",
  "| ratio | method | bias | MCSE | empirical SD | model SE | coverage | ESS |",
  "|---:|---|---:|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %s | %.4f | %.4f | %.3f | %.3f | %.3f | %.0f |", pl$ratio, pl$method, pl$bias,
          pl$mcse, pl$emp_sd, pl$mod_se, pl$cover, pl$ess), "")

## ---- P4 -----------------------------------------------------------------------
t0 <- proc.time()[["elapsed"]]
for (k in 1:40) fit_all(cell, draw(cell))
sec <- (proc.time()[["elapsed"]] - t0) / 40
out$P4 <- c(sec = sec, core_hours = nrow(g) * N_SIM * sec / 3600)
md <- c(md, "## P4: unit cost", "",
  sprintf("%.3f s per replicate, all methods; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")

saveRDS(out, "results/probes.rds")
writeLines(md, "results/probes.md")
cat(md, sep = "\n")
