## Probe: STC and MAIC sensitivity curves, feasibility and ESS, 30 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- do.call(rbind, replicate(30, fit_all(cc, draw(cc)), simplify = FALSE))
  a <- aggregate(cbind(stc, se_stc, maic, se_maic, feasible, ess) ~ p, r, mean); a$target <- sapply(SWEEP, function(p) target_logodds(p, cc$rho)); cbind(rho = cc$rho, a) }))
sec <- (proc.time()[["elapsed"]] - t0) / (30 * nrow(g))
md <- c("# QBA-13 probes", "", "Generated by `R/01-probes.R`, 30 replicates per cell. Means along the sweep of the assumed target prevalence p (true 0.5).", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.2f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
