## Probes: exact per-contrast bias under both sets for every cell, a simulation
## check against it, and unit cost. Writes results/probes.md.
source("R/00-model.R")
g <- build_grid()
ex <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) {
  cc <- g[i, ]; R <- reported(cc); I <- apply(R, 1, all); th <- truth(cc)
  bm <- vapply(1:K, function(k) exact_bias(cc, R[, k], k), 0)
  bi <- vapply(1:K, function(k) exact_bias(cc, I, k), 0)
  ## ranking read off noiseless biased contrasts
  data.frame(cell = cc$cell, pattern = cc$pattern, strength = cc$strength,
             similarity = cc$similarity, separation = cc$separation,
             mean_abs_bias_max = mean(abs(bm)), mean_abs_bias_int = mean(abs(bi)),
             top_wrong_max = which.max(th + bm) != which.max(th),
             top_wrong_int = which.max(th + bi) != which.max(th),
             spread_bias_max = diff(range(bm)), spread_bias_int = diff(range(bi)))
}))
set.seed(4); t0 <- proc.time()[["elapsed"]]
chk <- do.call(rbind, lapply(c(which(g$pattern == "adversarial" & g$strength == 0.5 &
                                    g$similarity == "similar" & g$separation == "tied")), function(i) {
  cc <- g[i, ]; R <- reported(cc); I <- apply(R, 1, all); th <- truth(cc)
  r <- lapply(1:100, function(z) fit_all(cc, draw(cc)))
  est_m <- rowMeans(sapply(r, function(z) z$max_est)); est_i <- rowMeans(sapply(r, function(z) z$int_est))
  data.frame(k = 1:K, sim_bias_max = est_m - th,
             exact_max = vapply(1:K, function(k) exact_bias(cc, R[, k], k), 0),
             sim_bias_int = est_i - th, exact_int = vapply(1:K, function(k) exact_bias(cc, I, k), 0))
}))
sec <- (proc.time()[["elapsed"]] - t0) / 100
md <- c("# COV-14 probes", "", "Generated by `R/01-probes.R`.", "",
  "## Exact bias by cell (no sampling noise)", "",
  "| pattern | strength | similarity | separation | mean abs bias, maximal | mean abs bias, intersection | bias spread, maximal | bias spread, intersection | top wrong, maximal | top wrong, intersection |",
  "|---|---:|---|---|---:|---:|---:|---:|:--:|:--:|",
  sprintf("| %s | %.2f | %s | %s | %.3f | %.3f | %.3f | %.3f | %s | %s |", ex$pattern, ex$strength,
          ex$similarity, ex$separation, ex$mean_abs_bias_max, ex$mean_abs_bias_int,
          ex$spread_bias_max, ex$spread_bias_int, ex$top_wrong_max, ex$top_wrong_int), "",
  "## Simulation against exact bias (adversarial, strength 0.5, similar, tied; 100 replicates)", "",
  "| comparator | simulated, maximal | exact, maximal | simulated, intersection | exact, intersection |",
  "|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.3f | %.3f | %.3f | %.3f |", chk$k, chk$sim_bias_max, chk$exact_max,
          chk$sim_bias_int, chk$exact_int), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
