## Probe: coverage overall and in the unsupported tail, infinite intervals, ESS; 40 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { r <- do.call(rbind, replicate(40, one_rep(g[i, ]), simplify = FALSE))
  a <- aggregate(cbind(coverage, coverage_tail, infinite, tail_infinite, median_width, ess_cal) ~ method, r, mean, na.action = na.pass); cbind(mu = g$mu[i], a) }))
sec <- (proc.time()[["elapsed"]] - t0) / (40 * nrow(g))
md <- c("# ADJ-04 probes", "", "Generated by `R/01-probes.R`, 40 replicates per shift. Nominal coverage 0.9.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---", ncol(rows)), collapse = ""),
  apply(rows, 1, function(r) paste("|", paste(c(r[1:2], sprintf("%.3f", as.numeric(r[-(1:2)]))), collapse = " | "), "|")), "",
  sprintf("Unit cost %.2f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
