## Probe: spread, SE and coverage of the correct and naive analyses, 2000 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- t(replicate(2000, fit_all(draw(cc))))
  data.frame(M = cc$M, n_c = cc$n_c, sd_right = stats::sd(r[, 1]), se_right = mean(r[, 2]), cov_right = mean(abs(r[, 1] - D_AC) <= 1.96 * r[, 2]),
             sd_naive = stats::sd(r[, 3]), se_naive = mean(r[, 4]), cov_naive = mean(abs(r[, 3] - D_AC) <= 1.96 * r[, 4]), sign_disagree = mean(sign(r[, 1]) != sign(r[, 3]))) }))
sec <- (proc.time()[["elapsed"]] - t0) / (2000 * nrow(g))
md <- c("# HET-02 probes", "", "Generated by `R/01-probes.R`, 2000 replicates per cell.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  "A first probe used the wrong sign for the covariance between trial 1's B-versus-C contrast and the pseudo-contrasts (both subtract the same C-arm mean, so it is +Var); it was corrected before this run.", "",
  sprintf("Unit cost %.5f s per replicate; %d cells at %d replicates is %.3f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
