## Probe: bias, package interval coverage and SE, correct augmentation, 12 replicates per cell,
## and the identity check of drMAIC's DR estimate against its MAIC estimate.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; tr <- truth(cc); r <- t(replicate(12, fit_all(cc, draw(cc))))
  data.frame(weights = cc$weights, outcome = cc$outcome, m1_t = cc$m1_t, truth = tr, bias_maic = mean(r[, 1]) - tr, bias_dr = mean(r[, 2]) - tr,
             max_abs_dr_minus_maic = max(abs(r[, 3])), pkg_coverage = mean(r[, 4] <= tr & tr <= r[, 5]), pkg_se = mean(r[, 6]),
             bias_aug = mean(r[, 7]) - tr, sd_aug = stats::sd(r[, 7])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (12 * nrow(g))
md <- c("# SFW-14 probes", "", "Generated by `R/01-probes.R` with drMAIC 0.1.0, 12 replicates per cell (bias columns are noisy at this size).", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---", ncol(rows)), collapse = ""),
  apply(rows, 1, function(r) paste("|", paste(c(r[1:3], formatC(as.numeric(r[-(1:3)]), format = "g", digits = 3)), collapse = " | "), "|")), "",
  sprintf("Unit cost %.2f s per replicate with %d bootstrap resamples for the correct estimator.", sec, N_BOOT), "")
writeLines(md, "results/probes.md")
