## Probe: bias of each method by detection sensitivity, visiting and true difference, 80 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; tr <- truth(cc); r <- t(replicate(80, fit_all(cc)))
  data.frame(se_b = cc$se_b, visiting = cc$visiting, effect = cc$effect, truth = tr, t(colMeans(r) - tr)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (80 * nrow(g))
md <- c("# QBA-07 probes", "", "Generated by `R/01-probes.R`, 80 replicates per cell. Bias of the RMST(24) difference in months.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---", ncol(rows)), collapse = ""),
  apply(rows, 1, function(r) paste("|", paste(c(r[1:3], sprintf("%.2f", as.numeric(r[-(1:3)]))), collapse = " | "), "|")), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
