## Probe: bridge bias and the leave-one-out winner's distribution, 200 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1)
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- t(replicate(200, fit_all(cc, draw(cc))))
  data.frame(eta = cc$eta, gz = cc$gz, bridge_bias = mean(r[, 1]) - D_CA, t(setNames(tabulate(r[, 5], 3) / 200, names(fitters)))) }))
md <- c("# DIS-11 probes", "", "Generated by `R/01-probes.R`, 200 replicates. Share of analyses in which each candidate wins by leave-one-trial-out log predictive density.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "")
writeLines(md, "results/probes.md")
