## Probe: bias and coverage by method in the cells that separate the failures;
## unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(16); print(g)
pick <- g[g$b == 0.4, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; tr <- truths(cc)
  r <- do.call(rbind, lapply(1:150, function(k) fit_all(draw(cc))))
  do.call(rbind, lapply(split(r, r$method), function(z) data.frame(part = cc$part, theta = cc$theta,
    pi_s = cc$pi_s, pi_t = cc$pi_t, method = z$method[1],
    bias_rr = mean(z$log_rr - tr[["log_rr"]], na.rm = TRUE),
    cover_rr = mean(abs(z$log_rr - tr[["log_rr"]]) <= 1.96 * z$se_rr, na.rm = TRUE),
    bias_rateA = mean(z$log_rate_A - log(tr[["rate_A"]]), na.rm = TRUE),
    cover_rateA = mean(abs(z$log_rate_A - log(tr[["rate_A"]])) <= 1.96 * z$se_rate_A, na.rm = TRUE))))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (150 * nrow(pick))
md <- c("# OUT-08 probes", "", "Generated by `R/01-probes.R`. Modification 0.4, 150 replicates.", "",
  "| part | theta | pi source | pi target | method | bias log RR | coverage | bias log rate A | coverage |",
  "|---|---:|---:|---:|---|---:|---:|---:|---:|",
  sprintf("| %s | %s | %.1f | %.1f | %s | %.4f | %.3f | %.4f | %.3f |", rows$part, rows$theta, rows$pi_s, rows$pi_t,
          rows$method, rows$bias_rr, rows$cover_rr, rows$bias_rateA, rows$cover_rateA), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
