## Probes: the pinned cSTC edge against an independent glm, the GLS pass-through
## row against discomb, one replicate per cell in both methods, the null control
## on 20 replicates, predicted bias per cell (P1), unit cost. Writes results/probes.md.
source("R/00-model.R"); g <- build_grid(); out <- c("# CMP-26 probes", "", "Generated by `R/01-probes.R`; cpaic cf27b1a (sourced copies), netmeta ", as.character(utils::packageVersion("netmeta")), ".", "")
out <- c(out[1:2], paste0(out[3:5], collapse = ""), "")

## Cross-checks on one dataset (null cell).
set.seed(1); cc <- g[g$name == "null", ]; d <- draw(cc)
pin <- t(vapply(seq_along(d), function(t) cstc_edge(d[[t]], t, cc$xt), numeric(2)))
ind <- t(vapply(seq_along(d), function(t) { z <- d[[t]]; z$a <- as.numeric(z$arm == TRIALS$t1[t]); z$xc <- z$x - cc$xt
  f <- stats::glm(y ~ a + xc + a:xc, family = stats::binomial(), data = z); c(stats::coef(f)[["a"]], sqrt(stats::vcov(f)["a", "a"])) }, numeric(2)))
b <- bridge(pin); gls <- sum(h_row(pin[, "seTE"]) * pin[, "TE"])
out <- c(out, "## Cross-checks (one dataset)", "",
  sprintf("- cSTC edges, pinned cpaic function against an independent glm: largest absolute difference %.1e (TE), %.1e (SE).", max(abs(pin[, 1] - ind[, 1])), max(abs(pin[, 2] - ind[, 2]))),
  sprintf("- A+D vs P, discomb common effect %.6f against GLS row h'TE %.6f: difference %.1e.", b[["est"]], gls, abs(b[["est"]] - gls)),
  sprintf("- Rank map: estimand A+D vs P estimable %s; component C estimable %s.", estimable(M_VEC), estimable(c(0, 0, 1, 0))), "")

## One replicate per cell, both methods, timed; predicted bias (P1).
t0 <- proc.time()[["user.self"]]
one <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { set.seed(100 + i); z <- one_rep(g[i, ]); z$name <- g$name[i]; z$truth <- truth(g[i, ]); z }))
sec <- (proc.time()[["user.self"]] - t0) / nrow(g)
out <- c(out, "## One replicate per cell", "", "| cell | method | truth | estimate | SE | predicted bias | error |", "|---|---|---:|---:|---:|---:|---|",
  sprintf("| %s | %s | %.3f | %.3f | %.3f | %.3f | %s |", one$name, one$method, one$truth, one$est, one$se, one$pred, ifelse(is.na(one$error), "", one$error)), "")

## Null control, 20 replicates.
nr <- do.call(rbind, lapply(1:20, function(k) { set.seed(MASTER_SEED %% 1e6 + 7919L * k + 104729L * 99L); one_rep(cc) }))
nr <- nr[nr$method == "cstc", ]; e <- nr$est - truth(cc)
out <- c(out, "## Null control (20 replicates, cSTC)", "",
  sprintf("- bias %.3f (MCSE %.3f), predicted %.3f, coverage %.2f, mean SE %.3f against empirical SD %.3f, failed %d.", mean(e, na.rm = TRUE), stats::sd(e, na.rm = TRUE) / sqrt(sum(!is.na(e))),
          mean(nr$pred, na.rm = TRUE), mean(abs(e) <= 1.96 * nr$se, na.rm = TRUE), mean(nr$se, na.rm = TRUE), stats::sd(nr$est, na.rm = TRUE), sum(!is.na(nr$error))), "")

out <- c(out, "## Unit cost", "", sprintf("- %.2f CPU s per replicate (both methods) under a load average near 500 on 8 cores; registered run %d cells x %d = %.1f CPU hours.",
  sec, nrow(g), N_SIM, sec * nrow(g) * N_SIM / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
