## Probe: naive bias against the closed form in every cell (200 replicates), and
## unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(13)
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) {
  cc <- g[i, ]; th <- truth(cc)
  r <- do.call(rbind, lapply(1:200, function(k) fit_all(cc, draw(cc))))
  nv <- r[r$method == "naive", ]; rc <- r[r$method == "reliability_corrected", ]
  data.frame(scen = cc$scen, rel = cc$rel, beta = cc$beta, predicted = predicted_bias(cc),
             naive = mean(nv$est) - th, mcse = stats::sd(nv$est) / sqrt(nrow(nv)),
             corrected = mean(rc$est, na.rm = TRUE) - th)
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(g))
md <- c("# COV-09 probes", "", "Generated by `R/01-probes.R`. 200 replicates per cell.", "",
  "| scenario | reliability | beta | predicted naive bias | naive bias | MCSE | corrected bias |", "|---|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.1f | %.1f | %.4f | %.4f | %.4f | %.4f |", rows$scen, rows$rel, rows$beta, rows$predicted,
          rows$naive, rows$mcse, rows$corrected), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
