## Probe: variance estimators against the empirical SD, and the induced-estimand
## gap under trimming, at poor overlap; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(8)
pick <- g[g$shift == 0.8 & g$prev == 0.3 & g$em == 1, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; tr <- truths(cc)
  r <- do.call(rbind, lapply(1:200, function(k) fit(cc, draw(cc))))
  data.frame(align = cc$align, trim = cc$trim, target = tr[["target"]], induced = tr[["induced"]],
             bias_target = mean(r[, "est"]) - tr[["target"]], bias_induced = mean(r[, "est"]) - tr[["induced"]],
             emp_sd = stats::sd(r[, "est"]), fixed = mean(r[, "se_fixed"]), ess = mean(r[, "se_ess"]),
             stack = mean(r[, "se_stack"]), hc1 = mean(r[, "se_stack_hc1"]))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(pick))
md <- c("# SFW-10 probes", "", "Generated by `R/01-probes.R`. Shift 0.8, prevalence 0.3, modification 1, 200 replicates.", "",
  "| alignment | trimming | target truth | induced truth | bias vs target | bias vs induced | empirical SD | mean SE fixed | ESS-based | stacked | stacked HC1 |",
  "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %s | %.3f | %.3f | %.4f | %.4f | %.3f | %.3f | %.3f | %s | %s |", rows$align, rows$trim, rows$target,
          rows$induced, rows$bias_target, rows$bias_induced, rows$emp_sd, rows$fixed, rows$ess,
          ifelse(is.na(rows$stack), "", sprintf("%.3f", rows$stack)), ifelse(is.na(rows$hc1), "", sprintf("%.3f", rows$hc1))), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
