## Probe: bias, coverage and width by prior, 40 replicates per cell; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; tr <- truth(cc); r <- do.call(rbind, replicate(40, fit_all(cc, draw(cc)), simplify = FALSE))
  a <- aggregate(cbind(bias = est - tr, coverage = lo <= tr & tr <= hi, width = hi - lo) ~ method, r, mean); cbind(n = cc$n, pattern = cc$pattern, a) }))
sec <- (proc.time()[["elapsed"]] - t0) / (40 * nrow(g))
md <- c("# COV-04 probes", "", "Generated by `R/01-probes.R`, 40 replicates per cell.", "",
  "| n per arm | pattern | method | bias | coverage | width |", "|---:|---|---|---:|---:|---:|",
  sprintf("| %d | %s | %s | %.3f | %.3f | %.3f |", rows$n, rows$pattern, rows$method, rows$bias, rows$coverage, rows$width), "",
  sprintf("Unit cost %.2f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
