## Probe: bias of the within and combined estimators and the influence diagnostic,
## IPD share 0.25, 200 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$share == 0.25), function(i) { cc <- g[i, ]; r <- t(replicate(200, fit_all(draw(cc))))
  data.frame(s_obs = cc$s_obs, s_lat = cc$s_lat, bias_beta_within = mean(r[, 1]) - BETA, bias_beta_comb = mean(r[, 4]) - BETA,
             bias_target_within = mean(r[, 3]) - (DELTA + BETA * X_T), bias_target_comb = mean(r[, 5]) - (DELTA + BETA * X_T),
             influence = mean(r[, "influence"], na.rm = TRUE), cov_within = mean(abs(r[, 1] - BETA) <= 1.96 * r[, 2])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(rows))
md <- c("# CMP-22 probes", "", "Generated by `R/01-probes.R`. IPD share 0.25, 200 replicates.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
