## Probe: bias and coverage of the exchangeable-baseline bridge with and without design adjustment,
## ten trials per subnetwork, 400 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$K == 10), function(i) { cc <- g[i, ]; r <- t(replicate(400, fit_all(cc, draw(cc)))); tr <- truth()
  data.frame(eta = cc$eta, overlap = cc$overlap, drift = cc$drift, bias_exch = mean(r[, 1]) - tr, cov_exch = mean(abs(r[, 1] - tr) <= 1.96 * r[, 2]),
             bias_adj = mean(r[, 3], na.rm = TRUE) - tr, cov_adj = mean(abs(r[, 3] - tr) <= 1.96 * r[, 4], na.rm = TRUE), adj_possible = mean(!is.na(r[, 3]))) }))
sec <- (proc.time()[["elapsed"]] - t0) / (400 * nrow(rows))
md <- c("# DIS-03 probes", "", "Generated by `R/01-probes.R`. Ten trials per subnetwork, 400 replicates. Adjustment is impossible when the design covariate does not vary within either subnetwork.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.3f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
