## P1 design census (no outcomes), P2 no-drift null and P3 drift replicates on a
## few draws per network, P4 unit cost. The real holdout statistics are not computed.
## Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); set.seed(1); R_P <- 8L; cpu_tot <- 0
out <- c("# Probes", "", "Generated by `R/01-probes.R`. The holdout statistics of the real outcomes are not computed here.", "",
  "| network | studies | arms | treatments | years | holdout units | null S median | null S range | naive raw-slope rejections | drift S median | CPU s per replicate |", "|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|")
for (n in names(NETS)) { d <- NETS[[n]]
  t0 <- proc.time()[["user.self"]]; nl <- t(replicate(R_P, summarize_h(holdouts(simulate_net(d, n), n)))); cpu <- (proc.time()[["user.self"]] - t0) / R_P; cpu_tot <- cpu_tot + cpu
  ps <- t(replicate(R_P, summarize_h(holdouts(simulate_net(d, n, DRIFT), n))))
  out <- c(out, sprintf("| %s | %d | %d | %d | %d to %d | %d | %.4f | %.4f to %.4f | %d of %d | %.4f | %.2f |", n, length(unique(d$study)), nrow(d), length(unique(d$trt)), min(d$year), max(d$year),
    nrow(units_for(d)), stats::median(nl[, "S"]), min(nl[, "S"]), max(nl[, "S"]), sum(nl[, "p_raw"] < 0.05), R_P, stats::median(ps[, "S"]), cpu)) }
out <- c(out, "", sprintf("Registered run: %d no-drift and %d drift replicates per network, about %.2f CPU hours (%d replicates per network here; heavily loaded shared machine).",
  R_NULL, R_POS, (R_NULL + R_POS) * sum(cpu_tot) / 3600, R_P), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
