## Individual-level check of the exact computation: standard errors, pass rate and
## coverage of the pooled interval given a pass, in four configurations.
source("R/00-model.R")
BETA_W <- 0.2; D0 <- -0.3
one_net <- function(K, disp, n, delta) {
  xm <- stats::qnorm((seq_len(K) - 0.5) / K) * disp
  bw <- numeric(K); vw <- numeric(K); dk <- numeric(K); vd <- numeric(K)
  for (k in seq_len(K)) {
    A <- rep(0:1, each = n / 2); x <- xm[k] + stats::rnorm(n)
    y <- stats::rnorm(1) + 0.5 * x + A * (D0 + BETA_W * (x - xm[k]) + (BETA_W + delta) * xm[k]) + stats::rnorm(n)
    f <- stats::lm(y ~ I(x - xm[k]) * A); cf <- stats::coef(f); V <- stats::vcov(f)
    bw[k] <- cf[4]; vw[k] <- V[4, 4]; dk[k] <- cf[3]; vd[k] <- V[3, 3]
  }
  bW <- sum(bw / vw) / sum(1 / vw); sW <- sqrt(1 / sum(1 / vw))
  m <- stats::lm(dk ~ xm, weights = 1 / vd)
  bA <- unname(stats::coef(m)[2]); sA <- sqrt(1 / sum((xm - stats::weighted.mean(xm, 1 / vd))^2 / vd))
  c(bW = bW, sW = sW, bA = bA, sA = sA)
}
set.seed(12)
cfgs <- data.frame(K = c(5, 20, 5, 20), disp = c(0.75, 0.75, 0.25, 0.25), delta = c(0.2, 0.2, 0, 0))
out <- do.call(rbind, lapply(seq_len(nrow(cfgs)), function(i) {
  cc <- cfgs[i, ]
  r <- t(replicate(2000, one_net(cc$K, cc$disp, 200L, cc$delta)))
  pass <- abs(r[, "bW"] - r[, "bA"]) < 0.5 * r[, "sA"]
  sP <- 1 / sqrt(1 / r[, "sW"]^2 + 1 / r[, "sA"]^2)
  bP <- (r[, "bW"] / r[, "sW"]^2 + r[, "bA"] / r[, "sA"]^2) * sP^2
  covP <- abs(bP - BETA_W) < 1.96 * sP
  s <- ses(cc$K, cc$disp, 200L)
  ex <- oc(s[["sW"]], s[["sA"]], s[["sd_d"]], cc$delta, rules$half_sA)
  data.frame(K = cc$K, disp = cc$disp, delta = cc$delta,
             sW_sim = mean(r[, "sW"]), sW_formula = s[["sW"]], sA_sim = mean(r[, "sA"]), sA_formula = s[["sA"]],
             pass_sim = mean(pass), pass_exact = ex[["pass"]],
             condcov_sim = mean(covP[pass]), condcov_exact = ex[["cond_cover_pass"]])
}))
md <- c("# MOD-15 check", "", "Generated by `R/01-check.R`. 2000 individual-level networks per row, 100 per arm.", "",
  "| K | dispersion | delta | sW sim | sW formula | sA sim | sA formula | pass sim | pass exact | coverage given pass, sim | exact |",
  "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.2f | %.1f | %.4f | %.4f | %.4f | %.4f | %.3f | %.3f | %.3f | %.3f |", out$K, out$disp, out$delta,
          out$sW_sim, out$sW_formula, out$sA_sim, out$sA_formula, out$pass_sim, out$pass_exact,
          out$condcov_sim, out$condcov_exact), "")
writeLines(md, "results/check.md"); cat(md, sep = "\n")
