## P1 SE and the tipping surface at the box corners; the identities (one mechanism:
## OAT = box = ball thresholds; box verdict = L-infinity min-norm > 1); P2 grid
## resolution of the thresholds; P3 order dependence of sequential single-bias
## corrections; P4 smoke replicates in the primary cells, predicted primary, cost.
## Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); g <- build_grid(); set.seed(MASTER_SEED); out <- c("# Probes", "", "Generated by `R/01-probes.R`.", "")
C <- as.matrix(expand.grid(g_u = c(-1, 1), m = c(0, 0.2), q = c(0, 0.4)))
out <- c(out, "## P1 standard error and tipping surface", "", sprintf("- SE_HAT (delta method, 300 per arm, no bias): %.4f", SE_HAT),
  sprintf("- S at the eight box corners (g_u, m, q): %s", paste(sprintf("(%g, %g, %g) %.3f", C[, 1], C[, 2], C[, 3], S_tip(C)), collapse = "; ")),
  sprintf("- S on the axes at the box edge: g_u = -1 %.3f, g_u = 1 %.3f, m = 0.2 %.3f, q = 0.4 %.3f", S_tip(rbind(c(-1, 0, 0)))[1], S_tip(rbind(c(1, 0, 0))), S_tip(rbind(c(0, 0.2, 0))), S_tip(rbind(c(0, 0, 0.4)))))
## One mechanism active (g_u alone): the cross, the box and the ball are one segment.
one <- list(p = 1L, rho = 0, cell = 99L); active <- function(cell) if (cell$p == 3L) c(TRUE, TRUE, TRUE) else if (cell$p == 2L) c(TRUE, TRUE, FALSE) else c(TRUE, FALSE, FALSE)
P1 <- prep(one)
out <- c(out, sprintf("- one mechanism: OAT, box and ball thresholds (lo, hi) %s; identical: %s",
  paste(sprintf("%.4f", c(P1$t_oat, P1$t_box, P1$t_ball)), collapse = ", "), isTRUE(all.equal(P1$t_oat, P1$t_box)) && isTRUE(all.equal(P1$t_box, P1$t_ball))), "")

## P2 grid resolution: thresholds on the registered grid against a grid twice as fine.
pc <- g[g$p == 3 & g$world == "calibrated" & g$dependence != "independent", ]
res <- do.call(rbind, lapply(unique(pc$dependence), function(dp) { cc <- pc[pc$dependence == dp, ][1, ]
  a <- prep(cc); b <- prep(cc, 2L * K_AX - 1L)
  data.frame(dependence = dp, rule = c("oat", "box", "ball", "frac"),
             lo = c(a$t_oat[1], a$t_box[1], a$t_ball[1], a$t_frac[1]), hi = c(a$t_oat[2], a$t_box[2], a$t_ball[2], a$t_frac[2]),
             lo_fine = c(b$t_oat[1], b$t_box[1], b$t_ball[1], b$t_frac[1]), hi_fine = c(b$t_oat[2], b$t_box[2], b$t_ball[2], b$t_frac[2])) }))
out <- c(out, "## P2 thresholds, registered grid (41 x 21 x 21 over twice the box) against a grid twice as fine", "",
  "| dependence | rule | lower | upper | lower, fine | upper, fine |", "|---|---|---:|---:|---:|---:|",
  sprintf("| %s | %s | %.4f | %.4f | %.4f | %.4f |", res$dependence, res$rule, res$lo, res$hi, res$lo_fine, res$hi_fine),
  "", sprintf("- largest threshold change: %.4f", max(abs(c(res$lo - res$lo_fine, res$hi - res$hi_fine)))), "")

## P3 sequential correction: apply each single-mechanism correction in turn, each as
## if its mechanism were the only one (solve L(d, gamma_j e_j) = theta, report
## T(d, g_u in that step)), in all six orders; the joint correction solves L(d, gamma).
corr <- function(th, G) { dd <- stats::uniroot(function(d) L_lim(d, G) - th, c(-6, 6), tol = 1e-10)$root; stats::qlogis(risk(MX_T, P_T, G[1, 1], dd)) - stats::qlogis(risk(MX_T, P_T, G[1, 1], 0)) }
perm <- list(1:3, c(1, 3, 2), c(2, 1, 3), c(2, 3, 1), c(3, 1, 2), c(3, 2, 1))
o3 <- do.call(rbind, lapply(c(-0.3, 0), function(th) do.call(rbind, lapply(seq_len(nrow(C)), function(i) { gm <- C[i, ]
  sq <- vapply(perm, function(pp) { v <- th; for (j in pp) { e <- rbind(c(0, 0, 0)); e[1, j] <- gm[j]; v <- corr(v, e) }; v }, 0)
  data.frame(theta = th, g_u = gm[1], m = gm[2], q = gm[3], joint = corr(th, rbind(gm)), seq_min = min(sq), seq_max = max(sq)) }))))
out <- c(out, "## P3 order dependence of sequential single-bias correction (box corners, theta_hat -0.3 and 0)", "",
  sprintf("- largest spread over the six orders: %.4f", max(o3$seq_max - o3$seq_min)),
  sprintf("- largest |sequential - joint|: %.4f", max(pmax(abs(o3$seq_max - o3$joint), abs(o3$seq_min - o3$joint)))), "")

## P4 smoke: 150 replicates in each primary cell; cost per replicate.
active <- function(cell) if (cell$p == 3L) c(TRUE, TRUE, TRUE) else c(TRUE, TRUE, FALSE)
t0 <- proc.time()
s <- do.call(rbind, lapply(seq_len(nrow(pc)), function(i) do.call(rbind, lapply(1:150, function(k) {
  set.seed(MASTER_SEED %% 1e6 + 7919L * k + 104729L * pc$cell[i]); transform(one_rep(pc[i, ]), cell = pc$cell[i]) }))))
tt <- proc.time() - t0; cpu <- (tt[["user.self"]] + tt[["sys.self"]]) / nrow(s)
fr <- vapply(c("oat", "box", "ball", "frac"), function(r) mean(s[[r]][s$flip]), 0)
ff <- vapply(c("oat", "box", "ball", "frac"), function(r) mean(!s[[r]][!s$flip]), 0)
out <- c(out, sprintf("## P4 smoke, primary cells (%s), 150 replicates each", paste(pc$cell, collapse = ", ")), "",
  sprintf("- flips: %d of %d", sum(s$flip), nrow(s)),
  sprintf("- false reassurance P(robust | flip): %s", paste(sprintf("%s %.3f", names(fr), fr), collapse = ", ")),
  sprintf("- false fragility P(fragile | no flip): %s", paste(sprintf("%s %.3f", names(ff), ff), collapse = ", ")),
  sprintf("- box verdict equals L-infinity min-norm > 1 in %d of %d replicates", sum(s$box == (s$minnorm_inf > 1 + 1e-9)), nrow(s)),
  sprintf("- ball and box verdicts disagree in %.3f of replicates", mean(s$ball != s$box)),
  sprintf("- CPU per replicate %.4f s including per-cell preparation, on a shared machine at load above 500", cpu),
  sprintf("- registered run: %d cells x %d replicates, about %.2f CPU-hours", nrow(g), N_SIM, nrow(g) * N_SIM * cpu / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
