## Probes: Monte Carlo covariance of the two adjusted contrasts against each
## method's estimate, coverage in two decisive cells, unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(9)
pick <- g[g$em == 0.6 & g$shift == 0.8 & g$nA_ratio == 0.5, ]
pick <- rbind(pick, g[g$em == 0 & g$shift == 0.8 & g$nA_ratio == 0.5, ])
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  R <- lapply(1:300, function(k) { d <- draw(cc); f <- fit_ipd(d$ipd, cc$shift); r <- fit_all(cc, d)
    list(est = f$est, cs = f$V_stack[1, 2], cf = f$V_fixed[1, 2], r = r) })
  E <- t(sapply(R, `[[`, "est"))
  cov_mc <- stats::cov(E[, 1], E[, 2])
  rr <- do.call(rbind, lapply(R, `[[`, "r"))
  bc <- rr[rr$contrast == "BC", ]
  cv <- tapply(abs(bc$est - th[["BC"]]) <= 1.96 * bc$se, bc$method, mean)
  data.frame(em = cc$em, align = cc$align, cov_mc = cov_mc, cov_stacked = mean(sapply(R, `[[`, "cs")),
             cov_fixed = mean(sapply(R, `[[`, "cf")),
             cover = paste(sprintf("%s %.3f", names(cv), cv), collapse = "; "))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# CMP-12 probes", "", "Generated by `R/01-probes.R`. Shift 0.8, shared arm half size, 300 replicates.", "",
  "| modification | alignment | MC covariance | stacked estimate | weights-fixed estimate | BC coverage by method |",
  "|---:|---|---:|---:|---:|---|",
  sprintf("| %.1f | %s | %.5f | %.5f | %.5f | %s |", rows$em, rows$align, rows$cov_mc, rows$cov_stacked,
          rows$cov_fixed, rows$cover), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
