<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Dropping failed or non-converged replicates makes every reported performance figure conditional on the method having worked, and when failure depends on scenario difficulty or on the size of the estimation error those figures can favor the more fragile method. The general solution is already published: Pawel et al.&nbsp;(arXiv:2409.18527; The American Statistician, doi:10.1080/00031305.2025.2540002) review 482 simulation studies, find that only 23% mention missingness at all, 19% report its frequency and 14% report how it was handled, propose a classification of failure types with handling options, and state the direction of the bias explicitly. What remains open is adoption in ITC and PAIC, where no equivalent review or typed failure reporting was found, plus one extension: their taxonomy does not separate a principled refusal to estimate a non-estimable contrast from a numerical convergence failure, and in this field that distinction carries scientific content.">

<title>Failed fits are deleted rather than classified and reported – Open Problems in ITC &amp; PAIC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3929247d43a275c44ef0022ded45a8ce.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ea0713af19bdf5f6adc2ec466a14144b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-3929247d43a275c44ef0022ded45a8ce.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Open Problems in ITC &amp; PAIC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../catalog.html"> 
<span class="menu-text">Catalog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-categories" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Categories</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-categories">    
        <li>
    <a class="dropdown-item" href="../categories/estimands.html">
 <span class="dropdown-text">Estimands &amp; target populations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/identification.html">
 <span class="dropdown-text">Identification, transitivity &amp; conditional constancy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/qba.html">
 <span class="dropdown-text">Quantitative bias analysis for unanchored PAIC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/overlap.html">
 <span class="dropdown-text">Positivity, overlap &amp; extrapolation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/covariates.html">
 <span class="dropdown-text">Covariates: selection, target moments, measurement</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/model-specification.html">
 <span class="dropdown-text">Model specification, double robustness &amp; targeted learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/heterogeneity.html">
 <span class="dropdown-text">Heterogeneity, consistency &amp; multi-arm structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/disconnected.html">
 <span class="dropdown-text">Disconnected networks &amp; bridges</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/component.html">
 <span class="dropdown-text">Component methods (CNMA and component PAIC)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/outcomes.html">
 <span class="dropdown-text">Outcome-specific problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/missing-data.html">
 <span class="dropdown-text">Missing data &amp; uncertainty propagation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/diagnostics.html">
 <span class="dropdown-text">Diagnostics &amp; empirical validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/computation.html">
 <span class="dropdown-text">Computation &amp; reproducibility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/decision.html">
 <span class="dropdown-text">Decision analysis, regulation &amp; reporting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/evidence-base.html">
 <span class="dropdown-text">Evidence-base construction &amp; data access</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/adjacent-methods.html">
 <span class="dropdown-text">Adjacent-field methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/software.html">
 <span class="dropdown-text">Software, benchmarks &amp; interface standards</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../agenda.html"> 
<span class="menu-text">Agenda</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../studies.html"> 
<span class="menu-text">Studies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chronology.html"> 
<span class="menu-text">Chronology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../landscape.html"> 
<span class="menu-text">Landscape</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods.html"> 
<span class="menu-text">How this was verified</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/choxos/ITC-open-problems"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#statement" id="toc-statement" class="nav-link active" data-scroll-target="#statement">Statement</a></li>
  <li><a href="#why-it-is-open" id="toc-why-it-is-open" class="nav-link" data-scroll-target="#why-it-is-open">Why it is open</a></li>
  <li><a href="#what-has-been-tried" id="toc-what-has-been-tried" class="nav-link" data-scroll-target="#what-has-been-tried">What has been tried</a></li>
  <li><a href="#probable-solution-or-research-direction" id="toc-probable-solution-or-research-direction" class="nav-link" data-scroll-target="#probable-solution-or-research-direction">Probable solution or research direction</a></li>
  <li><a href="#verification" id="toc-verification" class="nav-link" data-scroll-target="#verification">Verification</a></li>
  <li><a href="#how-the-evidence-falls-in-time" id="toc-how-the-evidence-falls-in-time" class="nav-link" data-scroll-target="#how-the-evidence-falls-in-time">How the evidence falls in time</a></li>
  <li><a href="#related-problems" id="toc-related-problems" class="nav-link" data-scroll-target="#related-problems">Related problems</a></li>
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source">Source</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Failed fits are deleted rather than classified and reported</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Computation &amp; reproducibility</div>
    <div class="quarto-category">Very high priority</div>
    <div class="quarto-category">Partially addressed</div>
  </div>
  </div>

<div>
  <div class="description">
    Dropping failed or non-converged replicates makes every reported performance figure conditional on the method having worked, and when failure depends on scenario difficulty or on the size of the estimation error those figures can favor the more fragile method. The general solution is already published: Pawel et al.&nbsp;(arXiv:2409.18527; The American Statistician, doi:10.1080/00031305.2025.2540002) review 482 simulation studies, find that only 23% mention missingness at all, 19% report its frequency and 14% report how it was handled, propose a classification of failure types with handling options, and state the direction of the bias explicitly. What remains open is adoption in ITC and PAIC, where no equivalent review or typed failure reporting was found, plus one extension: their taxonomy does not separate a principled refusal to estimate a non-estimable contrast from a numerical convergence failure, and in this field that distinction carries scientific content.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="problem-meta">
<p><span class="problem-id">CMU-05</span> <span class="verdict verdict-partially-addressed">Partially addressed</span> <span class="chip chip-priority-very-high">Very high priority</span> <span class="chip chip-maturity-established">Established</span></p>
</div>
<section id="statement" class="level2">
<h2 class="anchored" data-anchor-id="statement">Statement</h2>
<p>Dropping failed or non-converged replicates makes every reported performance figure conditional on the method having worked, and when failure depends on scenario difficulty or on the size of the estimation error those figures can favor the more fragile method. The general solution is already published: Pawel et al.&nbsp;(arXiv:2409.18527; The American Statistician, doi:10.1080/00031305.2025.2540002) review 482 simulation studies, find that only 23% mention missingness at all, 19% report its frequency and 14% report how it was handled, propose a classification of failure types with handling options, and state the direction of the bias explicitly. What remains open is adoption in ITC and PAIC, where no equivalent review or typed failure reporting was found, plus one extension: their taxonomy does not separate a principled refusal to estimate a non-estimable contrast from a numerical convergence failure, and in this field that distinction carries scientific content.</p>
</section>
<section id="why-it-is-open" class="level2">
<h2 class="anchored" data-anchor-id="why-it-is-open">Why it is open</h2>
<p>Failures are not missing at random with respect to the truth: separation, non-overlap, weak identification and sampler breakdown occur in the same cells that produce the largest errors, so deleting the failing method’s replicates while keeping the others’ flatters the method that failed. Software defaults reinforce the practice by returning NA values that pipelines drop without comment, and reviewers cannot detect the deletion because the per-cell replicate count is usually not reported. A conceptual problem also remains in what ‘reporting performance including failures’ means: an absent estimate has no bias and no interval coverage, so failure rates and conditional performance have to sit side by side unless a prespecified loss or worst-case rule combines them.</p>
</section>
<section id="what-has-been-tried" class="level2">
<h2 class="anchored" data-anchor-id="what-has-been-tried">What has been tried</h2>
<div class="table-scroll">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Work</th>
<th>What it contributes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://doi.org/10.1080/00031305.2025.2540002">Pawel, Bartos, Siepe and Lohmann 2025, Handling missingness, failures, and non-convergence in simulation studies (arXiv:2409.18527), The American Statistician</a></td>
<td>reviews 482 simulation studies (only 23% mention missingness, 19% report frequency, 14% report handling), proposes a classification of data-generating, method and performance missingness with handling options, and states that excluding results only for the non-convergent method may bias results in favor of that method</td>
</tr>
<tr class="even">
<td><a href="https://github.com/choxos/cpaic">cpaic, unreleased development package on GitHub (not on CRAN), commit 9d150e9</a></td>
<td>fails closed when too few MAIC bootstrap replicates succeed, on the ground that the standard error cannot then be trusted; it does not retain or publish replicate-level failure categories</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="probable-solution-or-research-direction" class="level2">
<h2 class="anchored" data-anchor-id="probable-solution-or-research-direction">Probable solution or research direction</h2>
<p>Apply the Pawel et al.&nbsp;classification per scenario cell instead of inventing a new one, and add the category it lacks: a principled refusal to estimate a non-estimable contrast, which is a scientific result rather than a numerical failure. Report the per-cell replicate count and the failure rate as a primary robustness measure alongside conditional performance, and combine the two into a single number only under a prespecified loss rule. The concrete missing artifact is a retained, published record of replicate-level failure categories; cpaic, an unreleased development package on GitHub that is not on CRAN, fails closed when too few bootstrap replicates succeed but does not keep those categories.</p>
</section>
<section id="verification" class="level2">
<h2 class="anchored" data-anchor-id="verification">Verification</h2>
<div class="verification-trail">
<p><strong>Verdict.</strong> Partially addressed. Auditors disagreed and the disagreement was evidence-bearing on both sides. Reopened by the full-text reading: 4 findings from 4 papers survived both the reader and an independent second reviewer, so the verdict moves from unverifiable to partially-addressed.</p>
<p><strong>The source said.</strong> “Simulation studies silently drop non-converged or failed replicates instead of publishing a classification of the failures, so every reported performance figure is conditional on the method having worked. That condition fails precisely in the hard scenarios the study exists to probe.”</p>
<p><strong>What was wrong with it.</strong> The source proposed a failure classification as new work. The literature auditor found that Pawel et al.&nbsp;2025 (arXiv:2409.18527) already published one together with the empirical evidence that failures go unreported, so the residual gap is adoption in this field; the ‘refusal to estimate’ category is this entry’s own extension and is not part of that taxonomy. The source-code auditor narrowed the bias claim: the direction follows only when failure is informative about difficulty or error, and it is not guaranteed as a theorem.</p>
<p><strong>Dissent.</strong> literature dissented (supported): I read the full PDF of Pawel, Bartos, Siepe &amp; Lohmann, ‘Handling Missingness, Failures, and Non-Convergence in Simulation Studies’ (arXiv:2409.18527v3; The American Statistician, doi 10.1080/00031305.2025.2540002). It supports the entry’s claims almost line for line and, crucially, it also does what the entry proposes: it reviews 482 simulation studies, finds only 23% mention missingness (19% report frequency, 14% report handling), proposes a classification of missingness types with handling options, and demonstrates in a case study that non-convergence is systematically driven by simulation factors. It states explicitly that deleting only the failing method’s replicates biases results in favor of that method, and cites the Peduzzi ‘ten events per variable’ rule as an influential result later shown to be driven by non-convergence handling. So the general-methodology solution now exists (2025) and the residual gap is adoption in ITC/PAIC, where I found no equivalent review. Caveat: the taxonomy distinguishes data-generating, method and performance missingness; it does not separately name ‘principled refusal to estimate a non-estimable contrast’, so that sub-claim is an extension, not a citation. codex dissented (open): C1 and C3 are sound methodological cautions. If failures are omitted, bias, RMSE, and coverage describe performance conditional on successful estimation rather than unconditional operational performance. C2 requires an explicit condition: the failure mechanism must depend on scenario difficulty, the latent estimation error, or both. The direction and effect on method ranking are not guaranteed mathematically. C4 is correct because principled abstention for a nonidentified estimand is scientifically different from numerical non-convergence. The direction’s request to report performance including failures also needs an operational definition: an absent estimate has no ordinary bias or interval coverage, so failure rates and conditional performance should be reported separately unless a prespecified loss or worst-case rule combines them. cpaic fails closed when too few MAIC bootstrap replicates succeed, but it does not retain and publish replicate-level failure categories, so the agenda item remains open.</p>
<p><strong>Revised by the full-text reading.</strong> Applied 2026-07-26 full-text reading of the consolidated library (687 papers).</p>
<dl>
<dt>Verdict changed</dt>
<dd>
<strong>unverifiable -&gt; partially-addressed</strong> 4 surviving findings from: Applying Quantitative Bias Analysis to Epidemiologic Data, S; Assessing the performance of population adjustment methods f; Paule-Mandel estimators for network meta-analysis with rando; Two-stage matching-adjusted indirect comparison. New citations: 10.1002/jrsm.1244, 10.1002/sim.8759, 10.1007/978-3-030-82673-4, 10.1186/s12874-022-01692-9
</dd>
<dt>Literature and prior-art check</dt>
<dd>
<strong>partially-solved / supported.</strong> I read the full PDF of Pawel, Bartos, Siepe &amp; Lohmann, ‘Handling Missingness, Failures, and Non-Convergence in Simulation Studies’ (arXiv:2409.18527v3; The American Statistician, doi 10.1080/00031305.2025.2540002). It supports the entry’s claims almost line for line and, crucially, it also does what the entry proposes: it reviews 482 simulation studies, finds only 23% mention missingness (19% report frequency, 14% report handling), proposes a classification of missingness types with handling options, and demonstrates in a case study that non-convergence is systematically driven by simulation factors. It states explicitly that deleting only the failing method’s replicates biases results in favor of that method, and cites the Peduzzi ‘ten events per variable’ rule as an influential result later shown to be driven by non-convergence handling. So the general-methodology solution now exists (2025) and the residual gap is adoption in ITC/PAIC, where I found no equivalent review. Caveat: the taxonomy distinguishes data-generating, method and performance missingness; it does not separately name ‘principled refusal to estimate a non-estimable contrast’, so that sub-claim is an extension, not a citation. Cites arxiv:2409.18527: Supplies both the empirical evidence that failures go unreported and the failure classification plus reporting recommendations that this entry proposes; published in The American Statistician (doi 10.1080/00031305.2025.2540002).. Cites arxiv:2409.18527: States the direction of the bias claimed by this entry..
</dd>
<dt>GPT-5.6 Sol, technical and source-code lens</dt>
<dd>
<strong>open / overstated.</strong> C1 and C3 are sound methodological cautions. If failures are omitted, bias, RMSE, and coverage describe performance conditional on successful estimation rather than unconditional operational performance. C2 requires an explicit condition: the failure mechanism must depend on scenario difficulty, the latent estimation error, or both. The direction and effect on method ranking are not guaranteed mathematically. C4 is correct because principled abstention for a nonidentified estimand is scientifically different from numerical non-convergence. The direction’s request to report performance including failures also needs an operational definition: an absent estimate has no ordinary bias or interval coverage, so failure rates and conditional performance should be reported separately unless a prespecified loss or worst-case rule combines them. cpaic fails closed when too few MAIC bootstrap replicates succeed, but it does not retain and publish replicate-level failure categories, so the agenda item remains open.
</dd>
<dt>Grok 4.5, recency lens</dt>
<dd>
<strong>open / supported.</strong> Pawel, Bartoš, Siepe &amp; Lohmann (arXiv:2409.18527v2; The American Statistician 2025) reviewed 482 methodological simulation studies (including RSM and SiM) and found only 23% mentioned missingness/failures, 19% quantified frequency, and 14% described handling; case-wise deletion was the modal strategy and can over-optimistically assess methods that fail on hard data. That paper classifies DGM/method/performance missingness and recommends always quantifying failures and treating failure rate as informative, which aligns with C1–C4 and strengthens rather than closes the agenda item. It is cross-field guidance with a meta-analysis case study, not an ITC/PAIC convention change or package default. Searches for PAIC/ML-NMR simulation papers that publish typed failure taxonomies (optimizer, non-convergence, separation, infeasible weights, principled refusal, integration failure) with performance both including and excluding failures found no field-wide adoption. Silent deletion and unreported per-cell replicate counts remain open practice problems as stated.
</dd>
<dt>Decision path</dt>
<dd>
<code>R3:partially-solved(n=1) → R7:counter-and-support-both-present</code>
</dd>
</dl>
</div>
</section>
<section id="how-the-evidence-falls-in-time" class="level2">
<h2 class="anchored" data-anchor-id="how-the-evidence-falls-in-time">How the evidence falls in time</h2>
<p>9 papers in the reviewed corpus bear on this problem, published 2012 to 2026. Partial progress is on the record, and later work still calls this open. Both belong in view.</p>
<p>This problem is <strong>recurrent</strong>: three or more papers spanning at least eight years assert it independently. Sustained restatement by authors who mostly do not cite each other is the strongest evidence this reading can offer that a gap is real rather than one group’s framing.</p>
<p>It is also being <strong>closed in pieces</strong>: partial results come from more than one paper in more than one year, each covering a different part.</p>
<div class="table-scroll">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Says</th>
<th>Paper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>confirms it is open</td>
<td>Simulation evaluation of statistical properties of methods for indirect and mixed treatment comparisons</td>
</tr>
<tr class="even">
<td>2017</td>
<td>partly addresses it</td>
<td>Paule-Mandel estimators for network meta-analysis with random inconsistency effects</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>confirms it is open</td>
<td>Hypothesis testing in Bayesian network meta-analysis</td>
</tr>
<tr class="even">
<td>2020</td>
<td>partly addresses it</td>
<td>Assessing the performance of population adjustment methods for anchored indirect comparisons: A simulation study</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>partly addresses it</td>
<td>Applying Quantitative Bias Analysis to Epidemiologic Data, Second Edition (Fox, MacLehose, Lash; Springer, Statistics for Biology and Health, 2021)</td>
</tr>
<tr class="even">
<td>2021</td>
<td>confirms it is open</td>
<td>Pattern-mixture model in network meta-analysis of binary missing outcome data: one-stage or two-stage approach?</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>partly addresses it</td>
<td>Two-stage matching-adjusted indirect comparison</td>
</tr>
<tr class="even">
<td>2024</td>
<td>confirms it is open</td>
<td>Methods for meta-analysis and meta-regression of binomial data: concepts and tutorial with Stata command metapreg</td>
</tr>
<tr class="odd">
<td>2026</td>
<td>confirms it is open</td>
<td>Bayesian Network Meta-Analysis With One or Two Continuous Outcomes Measured at Multiple Time Points Using Gaussian Random Walks With Drift</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="related-problems" class="level2">
<h2 class="anchored" data-anchor-id="related-problems">Related problems</h2>
<div class="related-links">
<ul>
<li><a href="../problems/DEC-13-published-paic-analyses-cannot-be-reconstructed-from-the-rec.html">DEC-13 — Published PAIC analyses cannot be reconstructed from the record</a></li>
<li><a href="../problems/QBA-18-maic-sensitivity-grids-infeasible-calibration-and-failed-fit.html">QBA-18 — MAIC sensitivity grids: infeasible calibration and failed fits</a></li>
</ul>
</div>
</section>
<section id="source" class="level2">
<h2 class="anchored" data-anchor-id="source">Source</h2>
<p>Derived from C:L2126, C:L2131 of the reviewed corpus.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/choxos\.github\.io\/ITC-open-problems\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Ahmad Sofi-Mahmudi</p>
</div>   
    <div class="nav-footer-center">
<p>Every entry carries a verification verdict. See <a href="../methods.html">How this was verified</a>.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/choxos/ITC-open-problems">Source</a></p>
</div>
  </div>
</footer>




</body></html>