<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A network meta-analysis reaches guideline panels, reimbursement committees and clinicians as a display rather than as a posterior, and no display carries a measured reading-error rate. A systematic survey of 200 reviews published in 2020 and 2021 counted 1133 presentation formats in use, with forest plots in 108 reviews (54.0 percent), league tables in 93 (46.5 percent) and the surface under the cumulative ranking curve in 69 (34.5 percent), while a structured evidence summary appeared in 10 (5.0 percent) and covered benefits and harms together in 3 (1.5 percent). New formats keep arriving, among them the rank-heat plot, the Kilim plot, spie charts, color-coded multi-outcome tables and interactive summary tools, and each is introduced with a worked example rather than with evidence that a reader extracts the right answer from it. Development studies stop at acceptability and preference: the GRADE network summary-of-findings table came out of four rounds of semistructured interviews with 32 stakeholders, two color-coded multi-outcome formats were refined by qualitative content analysis with 26 participants against a single exemplar network in acute pain, and the MATCH-IT interactive tool was revised over five cycles of think-aloud testing with 26 physicians, 24 of whom (94 percent) reported no or sparse prior experience of interpreting a network meta-analysis. One randomized comparison exists: 149 third-year medical students were assigned to two MATCH-IT versions differing in color coding and in which outcomes appear on entry, 82.5 percent answered at least 4 of 5 interpretation items correctly and 75.8 percent reached the recommendation an expert panel had reached, and the design contrast made no difference to interpretation or to understandability. Nothing compares display families against each other on one network, nothing scores whether a reader recognizes that a top-ranked treatment is imprecisely estimated or that a contrast is carried entirely by indirect evidence, and nothing has been run on the panels and committees the displays exist to serve.">

<title>Network meta-analysis displays are tested for acceptability, not for accuracy – Open Problems in ITC &amp; PAIC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-03d47695bc5f811f7e6896b5de8ee1f3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-9a2863f3190aa48dadd243fa71713907.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-03d47695bc5f811f7e6896b5de8ee1f3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Open Problems in ITC &amp; PAIC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../catalog.html"> 
<span class="menu-text">Catalog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-categories" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Categories</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-categories">    
        <li>
    <a class="dropdown-item" href="../categories/estimands.html">
 <span class="dropdown-text">Estimands &amp; target populations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/identification.html">
 <span class="dropdown-text">Identification, transitivity &amp; conditional constancy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/qba.html">
 <span class="dropdown-text">Quantitative bias analysis for unanchored PAIC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/overlap.html">
 <span class="dropdown-text">Positivity, overlap &amp; extrapolation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/covariates.html">
 <span class="dropdown-text">Covariates: selection, target moments, measurement</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/model-specification.html">
 <span class="dropdown-text">Model specification, double robustness &amp; targeted learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/heterogeneity.html">
 <span class="dropdown-text">Heterogeneity, consistency &amp; multi-arm structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/disconnected.html">
 <span class="dropdown-text">Disconnected networks &amp; bridges</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/component.html">
 <span class="dropdown-text">Component methods (CNMA and component PAIC)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/outcomes.html">
 <span class="dropdown-text">Outcome-specific problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/missing-data.html">
 <span class="dropdown-text">Missing data &amp; uncertainty propagation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/diagnostics.html">
 <span class="dropdown-text">Diagnostics &amp; empirical validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/computation.html">
 <span class="dropdown-text">Computation &amp; reproducibility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/decision.html">
 <span class="dropdown-text">Decision analysis, regulation &amp; reporting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/evidence-base.html">
 <span class="dropdown-text">Evidence-base construction &amp; data access</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/adjacent-methods.html">
 <span class="dropdown-text">Adjacent-field methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/software.html">
 <span class="dropdown-text">Software, benchmarks &amp; interface standards</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../agenda.html"> 
<span class="menu-text">Agenda</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chronology.html"> 
<span class="menu-text">Chronology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../landscape.html"> 
<span class="menu-text">Landscape</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods.html"> 
<span class="menu-text">How this was verified</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/choxos/ITC-open-problems"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#statement" id="toc-statement" class="nav-link active" data-scroll-target="#statement">Statement</a></li>
  <li><a href="#why-it-is-open" id="toc-why-it-is-open" class="nav-link" data-scroll-target="#why-it-is-open">Why it is open</a></li>
  <li><a href="#what-has-been-tried" id="toc-what-has-been-tried" class="nav-link" data-scroll-target="#what-has-been-tried">What has been tried</a></li>
  <li><a href="#probable-solution-or-research-direction" id="toc-probable-solution-or-research-direction" class="nav-link" data-scroll-target="#probable-solution-or-research-direction">Probable solution or research direction</a></li>
  <li><a href="#verification" id="toc-verification" class="nav-link" data-scroll-target="#verification">Verification</a></li>
  <li><a href="#related-problems" id="toc-related-problems" class="nav-link" data-scroll-target="#related-problems">Related problems</a></li>
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source">Source</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Network meta-analysis displays are tested for acceptability, not for accuracy</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Decision analysis, regulation &amp; reporting</div>
    <div class="quarto-category">Medium-high priority</div>
    <div class="quarto-category">Partially addressed</div>
  </div>
  </div>

<div>
  <div class="description">
    A network meta-analysis reaches guideline panels, reimbursement committees and clinicians as a display rather than as a posterior, and no display carries a measured reading-error rate. A systematic survey of 200 reviews published in 2020 and 2021 counted 1133 presentation formats in use, with forest plots in 108 reviews (54.0 percent), league tables in 93 (46.5 percent) and the surface under the cumulative ranking curve in 69 (34.5 percent), while a structured evidence summary appeared in 10 (5.0 percent) and covered benefits and harms together in 3 (1.5 percent). New formats keep arriving, among them the rank-heat plot, the Kilim plot, spie charts, color-coded multi-outcome tables and interactive summary tools, and each is introduced with a worked example rather than with evidence that a reader extracts the right answer from it. Development studies stop at acceptability and preference: the GRADE network summary-of-findings table came out of four rounds of semistructured interviews with 32 stakeholders, two color-coded multi-outcome formats were refined by qualitative content analysis with 26 participants against a single exemplar network in acute pain, and the MATCH-IT interactive tool was revised over five cycles of think-aloud testing with 26 physicians, 24 of whom (94 percent) reported no or sparse prior experience of interpreting a network meta-analysis. One randomized comparison exists: 149 third-year medical students were assigned to two MATCH-IT versions differing in color coding and in which outcomes appear on entry, 82.5 percent answered at least 4 of 5 interpretation items correctly and 75.8 percent reached the recommendation an expert panel had reached, and the design contrast made no difference to interpretation or to understandability. Nothing compares display families against each other on one network, nothing scores whether a reader recognizes that a top-ranked treatment is imprecisely estimated or that a contrast is carried entirely by indirect evidence, and nothing has been run on the panels and committees the displays exist to serve.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="problem-meta">
<p><span class="problem-id">DEC-34</span> <span class="verdict verdict-partially-addressed">Partially addressed</span> <span class="chip chip-priority-medium-high">Medium-high priority</span> <span class="chip chip-maturity-emerging">Emerging</span> <span class="chip">Tractability 4/5</span></p>
</div>
<section id="statement" class="level2">
<h2 class="anchored" data-anchor-id="statement">Statement</h2>
<p>A network meta-analysis reaches guideline panels, reimbursement committees and clinicians as a display rather than as a posterior, and no display carries a measured reading-error rate. A systematic survey of 200 reviews published in 2020 and 2021 counted 1133 presentation formats in use, with forest plots in 108 reviews (54.0 percent), league tables in 93 (46.5 percent) and the surface under the cumulative ranking curve in 69 (34.5 percent), while a structured evidence summary appeared in 10 (5.0 percent) and covered benefits and harms together in 3 (1.5 percent). New formats keep arriving, among them the rank-heat plot, the Kilim plot, spie charts, color-coded multi-outcome tables and interactive summary tools, and each is introduced with a worked example rather than with evidence that a reader extracts the right answer from it. Development studies stop at acceptability and preference: the GRADE network summary-of-findings table came out of four rounds of semistructured interviews with 32 stakeholders, two color-coded multi-outcome formats were refined by qualitative content analysis with 26 participants against a single exemplar network in acute pain, and the MATCH-IT interactive tool was revised over five cycles of think-aloud testing with 26 physicians, 24 of whom (94 percent) reported no or sparse prior experience of interpreting a network meta-analysis. One randomized comparison exists: 149 third-year medical students were assigned to two MATCH-IT versions differing in color coding and in which outcomes appear on entry, 82.5 percent answered at least 4 of 5 interpretation items correctly and 75.8 percent reached the recommendation an expert panel had reached, and the design contrast made no difference to interpretation or to understandability. Nothing compares display families against each other on one network, nothing scores whether a reader recognizes that a top-ranked treatment is imprecisely estimated or that a contrast is carried entirely by indirect evidence, and nothing has been run on the panels and committees the displays exist to serve.</p>
</section>
<section id="why-it-is-open" class="level2">
<h2 class="anchored" data-anchor-id="why-it-is-open">Why it is open</h2>
<p>A comprehension study needs an answer key, and the field has not agreed what a correct reading of a network result is. Scoring whether a reader took the right message from a ranking display presupposes a position on what a ranking licenses, and that position is contested: the same fit yields orderings that differ by ranking metric and by whether uncertainty is penalized, so the answer key would encode a judgment the field is still arguing about. The audience that matters is also the audience that cannot be recruited at scale, since guideline panels and reimbursement committees have members in the tens, read a display once inside a deliberation that is itself the outcome of interest, and cannot be randomized without disturbing the process being measured; the substitute available in hundreds is students, who are not the audience. Display work is done by the groups that build displays, and a head-to-head trial can only demote one of the entrants, so no one whose format is in use has an incentive to run it and no funder treats presentation evaluation as a methods output. The comparison also has no natural unit, because a league table and a rank-heat plot answer different questions from one fit, so a trial must first fix the question, which is the step on which agreement is missing.</p>
</section>
<section id="what-has-been-tried" class="level2">
<h2 class="anchored" data-anchor-id="what-has-been-tried">What has been tried</h2>
<div class="table-scroll">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Work</th>
<th>What it contributes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://doi.org/10.1016/j.jclinepi.2024.111445">Lovsletten, Wang, Pitre, Odegaard, Veroniki, Lunny, Tricco, Agoritsas &amp; Vandvik 2024, Journal of Clinical Epidemiology 173:111445</a></td>
<td>Systematic survey of 200 systematic reviews with network meta-analysis published 2020 to 2021 across 158 journals; counts 1133 presentation formats, forest plots in 108 reviews (54.0 percent), league tables in 93 (46.5 percent), SUCRA in 69 (34.5 percent), structured evidence summaries in 10 (5.0 percent) and in 3 (1.5 percent) across benefits and harms, absolute effects in 16 of 133 reviews reporting dichotomous outcomes (11.7 percent) and certainty ratings inside a presentation format in 26 (13.0 percent). Establishes what is in use; measures no comprehension.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1136/bmjebm-2023-112370">Stokke Hunskaar, Lovsletten, Muller &amp; Vandvik 2024, BMJ Evidence-Based Medicine 29(1):29-36</a></td>
<td>The only randomized comparison of network meta-analysis display design. 149 third-year medical students were randomized between two MATCH-IT versions, one using color coding to categorize interventions by magnitude and direction of effect with all outcomes shown on entry and one with neither; 82.5 percent (n=123) answered at least 4 of 5 interpretation items correctly, 75.8 percent (n=114) recommended what an expert panel recommended, and the design alternatives were preferred but had no bearing on interpretation or understandability. Compares two variants of one tool, not display families, and in students.</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1016/j.jclinepi.2024.111399">Lovsletten, Stokke Hunskaar, Heen, Bekkering, Vanden Poel, Zeraatkar, Vermandere, Aertgeerts, Delvaux, Achille, Busse, Agoritsas &amp; Vandvik 2024, Journal of Clinical Epidemiology 172:111399</a></td>
<td>Qualitative user testing of MATCH-IT over five development cycles with 26 practicing physicians in Norway, Belgium and Canada, 24 of whom (94 percent) had no or sparse prior experience of interpreting network meta-analysis; think-aloud plus semistructured interview with directed content analysis. Reports proof of concept and names comparison of MATCH-IT with similar tools and formats as the next step, which has not been done.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1136/bmjopen-2021-056400">Phillips, Sadeghirad, Busse, Brignardello-Petersen, Cuello-Garcia, Kenji Nampo, Guo, Bzovsky, Bannuru, Thabane, Bhandari &amp; Guyatt 2022, BMJ Open 12(6):e056400</a></td>
<td>Design validation of two color-coded formats for presenting minimally and partially contextualized network results across multiple outcomes, using qualitative content analysis of interviews with 26 participants including 20 practicing clinicians. Ends with two formats each preferred by a substantial group and no criterion for choosing between them; validated against a single exemplar network.</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1016/j.jclinepi.2019.04.018">Yepes-Nunez, Li, Guyatt, Jack, Brozek, Beyene, Murad, Rochwerg, Mbuagbaw, Zhang, Florez, Siemieniuk, Sadeghirad, Mustafa, Santesso &amp; Schunemann 2019, Journal of Clinical Epidemiology 115:1-13</a></td>
<td>Develops the GRADE summary-of-findings table for network meta-analysis through four rounds of semistructured interviews with 32 stakeholders who conduct or use meta-analysis, yielding six candidate tables and one judged highly acceptable. The endpoint is acceptability, not accuracy of reading.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1016/j.jclinepi.2016.02.016">Veroniki, Straus, Fyraridis &amp; Tricco 2016, Journal of Clinical Epidemiology 76:193-199</a></td>
<td>Introduces the rank-heat plot for many treatments across many outcomes in one figure and states that research on the understanding of the available approaches for presenting treatment ranking by clinicians, guideline developers and policy makers is needed and critical, because different approaches may complicate inference and decision-making. That research has not been carried out.</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1186/s12874-020-01128-2">Daly, Mbuagbaw, Thabane, Straus &amp; Hamid 2020, BMC Medical Research Methodology 20(1):266</a></td>
<td>Proof-of-concept framework plotting each treatment’s performance across outcomes as a spie chart whose coverage area represents the probability of ranking best overall, illustrated on dietary-fat and psoriasis networks. Concludes that formal validation in the decision-making context and statistical comparisons with other recent approaches are required, and neither has followed.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1002/jrsm.1428">Seo, Furukawa, Veroniki, Pillinger, Tomlinson, Salanti, Cipriani &amp; Efthimiou 2021, Research Synthesis Methods 12(1):86-95</a></td>
<td>The Kilim plot for multi-outcome network results, conveying uncertainty through a truncated color scale rather than intervals; states that it gives no relative effects and shows no confidence intervals, so what a reader can and cannot infer from it is a design decision that was never tested.</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1016/j.jclinepi.2015.12.007">Carrasco-Labra, Brignardello-Petersen, Santesso, Neumann, Mustafa, Mbuagbaw, Etxeandia Ikobaltzeta, De Stio, McCullagh, Alonso-Coello, Meerpohl, Vandvik, Brozek, Akl, Bossuyt, Churchill, Glenton, Rosenbaum, Tugwell, Welch, Garner, Guyatt &amp; Schunemann 2016, Journal of Clinical Epidemiology 74:7-18</a></td>
<td>Randomized trial among 290 systematic review users comparing a new and the current summary-of-findings table format on item-by-item understanding, accessibility, satisfaction and preference, with 63 percent and 62 percent more correct answers for the new format on understanding risk difference and understanding certainty. This is the design template the network display literature has not executed; it was run on pairwise tables.</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1186/s12874-020-0911-9">Kossmeier, Tran &amp; Voracek 2020, BMC Medical Research Methodology 20(1):26</a></td>
<td>Comprehensive review, taxonomy and feature analysis of graphical displays for meta-analysis and systematic reviews, correlating functionality features across the inventory; identifies displays that remain usable at medium to large numbers of studies while still identifying each study and its effect as rare. Maps the design space without evaluating any display against readers.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="probable-solution-or-research-direction" class="level2">
<h2 class="anchored" data-anchor-id="probable-solution-or-research-direction">Probable solution or research direction</h2>
<p>Fix the readings before the formats: name the small set of judgments a display must support, which treatment the evidence best supports, how uncertain that ordering is, what the absolute difference is at a stated baseline risk and horizon, and which contrasts rest on indirect evidence alone, then derive the answer key for each from the fitted model rather than from opinion. Run on displays the design already executed for tables: the randomized trial that compared summary-of-findings formats among 290 review users and scored understanding item by item transfers directly to a comparison of league table, forest plot against a common comparator, rankogram or cumulative ranking curve, rank-heat plot and an interactive summary, all built from one network at fixed certainty ratings. Report accuracy per reading with the direction of the error and the time taken, so that a display can be described the way a diagnostic is described and a review can state which readings its chosen format supports and which it does not. Recruit guideline panelists and health technology assessment reviewers as the primary stratum even at sample sizes in the low hundreds, and report student samples separately rather than as evidence about committees. The cheap first step is to start with the two formats that dominate the surveyed corpus of 200 reviews, the forest plot and the league table, since those are what readers actually meet.</p>
</section>
<section id="verification" class="level2">
<h2 class="anchored" data-anchor-id="verification">Verification</h2>
<div class="verification-trail">
<p><strong>Verdict.</strong> Partially addressed. This rests on labeller-reported absence rather than on a source arguing for it: 6 of 12 gap labellers independently named it after failing to find it while attaching future-work sentences to the registry, and the supporting sentences span 15 distinct papers from 2014 to 2026, most of them proposals of a display conceding that their own format was never evaluated with readers. Checked against the registry, where DEC-05 asks what a committee page should contain, OUT-21 asks what a set of absolute effects must have in common, DEC-23 and DEC-29 concern the certainty and the distortion of the hierarchy, and DEC-30 concerns the reliability of credibility labels; none asks whether any display is read correctly. The verdict is partially-addressed rather than confirmed-open because quantitative evaluation is not wholly absent: one randomized trial with 149 medical students compared two variants of one interactive tool, and three qualitative user-testing and design-validation studies exist with 26, 26 and 32 participants. What remains unevaluated is the choice between display families, the accuracy of any of them against a defined answer key, and behavior in the panels and committees that use them. Provenance here is weaker than for neighboring entries, since no source argues the gap as a methodological problem; the evidence is a repeated admission inside display proposals that validation was not done, plus one explicit call that the research is critical because different presentations may lead to different decisions.</p>
</div>
</section>
<section id="related-problems" class="level2">
<h2 class="anchored" data-anchor-id="related-problems">Related problems</h2>
<div class="related-links">
<ul>
<li><a href="../problems/DEC-05-committees-get-no-one-page-statement-of-what-an-estimate-res.html">DEC-05 — Committees get no one-page statement of what an estimate rests on</a></li>
<li><a href="../problems/DEC-23-the-treatment-hierarchy-is-published-without-a-certainty-rat.html">DEC-23 — The treatment hierarchy is published without a certainty rating</a></li>
<li><a href="../problems/DEC-29-ranking-metrics-reward-imprecision-and-no-correction-exists.html">DEC-29 — Ranking metrics reward imprecision and no correction exists</a></li>
<li><a href="../problems/DEC-30-rob-men-reliability-is-unmeasured-and-cinema-agreement-colla.html">DEC-30 — ROB-MEN reliability is unmeasured and CINeMA agreement collapses on large networks</a></li>
<li><a href="../problems/OUT-21-absolute-effects-across-a-network-share-no-baseline-risk-or-.html">OUT-21 — Absolute effects across a network share no baseline risk or time horizon</a></li>
</ul>
</div>
</section>
<section id="source" class="level2">
<h2 class="anchored" data-anchor-id="source">Source</h2>
<p>Derived from reading:uncovered of the reviewed corpus.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/choxos\.github\.io\/ITC-open-problems\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Ahmad Sofi-Mahmudi</p>
</div>   
    <div class="nav-footer-center">
<p>Every entry carries a verification verdict. See <a href="../methods.html">How this was verified</a>.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/choxos/ITC-open-problems">Source</a></p>
</div>
  </div>
</footer>




</body></html>