<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="No neutral field-wide benchmark exists that compares baseline connection, CNMA, component PAIC, reference prediction, dose-response models, class effects and partial identification under shared disconnected-network data-generating mechanisms, with public seeds, versioned expected outputs and analytic-truth unit tests. Package-local infrastructure of that kind does exist: at commit 9d150e9 cpaic, an unreleased development package on GitHub that is not on CRAN, ships seeded disconnected-network fixtures with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests and cross-package equivalence checks against maicplus. Independent comparative simulation also exists for parts of the field: Chandler and Proskorovsky (doi:10.1002/jrsm.1759) compared four families of MAIC variance estimator across 108 scenarios, and Liu et al.&nbsp;(doi:10.1007/s40258-025-00952-1) ran a 729-scenario full-factorial comparison of unanchored MAIC against naive indirect comparison, neither promoting a method of its own. What is missing is the neutral, maintained, cross-package suite that any implementation can be run against.">

<title>No neutral cross-package benchmark suite for PAIC implementations – Open Problems in ITC &amp; PAIC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-03d47695bc5f811f7e6896b5de8ee1f3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-9a2863f3190aa48dadd243fa71713907.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-03d47695bc5f811f7e6896b5de8ee1f3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Open Problems in ITC &amp; PAIC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../catalog.html"> 
<span class="menu-text">Catalog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-categories" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Categories</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-categories">    
        <li>
    <a class="dropdown-item" href="../categories/estimands.html">
 <span class="dropdown-text">Estimands &amp; target populations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/identification.html">
 <span class="dropdown-text">Identification, transitivity &amp; conditional constancy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/qba.html">
 <span class="dropdown-text">Quantitative bias analysis for unanchored PAIC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/overlap.html">
 <span class="dropdown-text">Positivity, overlap &amp; extrapolation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/covariates.html">
 <span class="dropdown-text">Covariates: selection, target moments, measurement</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/model-specification.html">
 <span class="dropdown-text">Model specification, double robustness &amp; targeted learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/heterogeneity.html">
 <span class="dropdown-text">Heterogeneity, consistency &amp; multi-arm structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/disconnected.html">
 <span class="dropdown-text">Disconnected networks &amp; bridges</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/component.html">
 <span class="dropdown-text">Component methods (CNMA and component PAIC)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/outcomes.html">
 <span class="dropdown-text">Outcome-specific problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/missing-data.html">
 <span class="dropdown-text">Missing data &amp; uncertainty propagation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/diagnostics.html">
 <span class="dropdown-text">Diagnostics &amp; empirical validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/computation.html">
 <span class="dropdown-text">Computation &amp; reproducibility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/decision.html">
 <span class="dropdown-text">Decision analysis, regulation &amp; reporting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/evidence-base.html">
 <span class="dropdown-text">Evidence-base construction &amp; data access</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/adjacent-methods.html">
 <span class="dropdown-text">Adjacent-field methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../categories/software.html">
 <span class="dropdown-text">Software, benchmarks &amp; interface standards</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../agenda.html"> 
<span class="menu-text">Agenda</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chronology.html"> 
<span class="menu-text">Chronology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../landscape.html"> 
<span class="menu-text">Landscape</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods.html"> 
<span class="menu-text">How this was verified</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/choxos/ITC-open-problems"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#statement" id="toc-statement" class="nav-link active" data-scroll-target="#statement">Statement</a></li>
  <li><a href="#why-it-is-open" id="toc-why-it-is-open" class="nav-link" data-scroll-target="#why-it-is-open">Why it is open</a></li>
  <li><a href="#what-has-been-tried" id="toc-what-has-been-tried" class="nav-link" data-scroll-target="#what-has-been-tried">What has been tried</a></li>
  <li><a href="#probable-solution-or-research-direction" id="toc-probable-solution-or-research-direction" class="nav-link" data-scroll-target="#probable-solution-or-research-direction">Probable solution or research direction</a></li>
  <li><a href="#verification" id="toc-verification" class="nav-link" data-scroll-target="#verification">Verification</a></li>
  <li><a href="#how-the-evidence-falls-in-time" id="toc-how-the-evidence-falls-in-time" class="nav-link" data-scroll-target="#how-the-evidence-falls-in-time">How the evidence falls in time</a></li>
  <li><a href="#related-problems" id="toc-related-problems" class="nav-link" data-scroll-target="#related-problems">Related problems</a></li>
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source">Source</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">No neutral cross-package benchmark suite for PAIC implementations</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Software, benchmarks &amp; interface standards</div>
    <div class="quarto-category">Very high priority</div>
    <div class="quarto-category">Partially addressed</div>
  </div>
  </div>

<div>
  <div class="description">
    No neutral field-wide benchmark exists that compares baseline connection, CNMA, component PAIC, reference prediction, dose-response models, class effects and partial identification under shared disconnected-network data-generating mechanisms, with public seeds, versioned expected outputs and analytic-truth unit tests. Package-local infrastructure of that kind does exist: at commit 9d150e9 cpaic, an unreleased development package on GitHub that is not on CRAN, ships seeded disconnected-network fixtures with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests and cross-package equivalence checks against maicplus. Independent comparative simulation also exists for parts of the field: Chandler and Proskorovsky (doi:10.1002/jrsm.1759) compared four families of MAIC variance estimator across 108 scenarios, and Liu et al.&nbsp;(doi:10.1007/s40258-025-00952-1) ran a 729-scenario full-factorial comparison of unanchored MAIC against naive indirect comparison, neither promoting a method of its own. What is missing is the neutral, maintained, cross-package suite that any implementation can be run against.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="problem-meta">
<p><span class="problem-id">SFW-04</span> <span class="verdict verdict-partially-addressed">Partially addressed</span> <span class="chip chip-priority-very-high">Very high priority</span> <span class="chip chip-maturity-emerging">Emerging</span> <span class="chip">Tractability 5/5</span></p>
</div>
<div class="source-unsourced">
<p><strong>Source note.</strong> This entry derives in part from a source document whose inline citations were ChatGPT interface tokens rather than references, and so resolve to nothing. Claims below are attributed to that document and were checked independently where possible; anything that could not be independently sourced is marked in the verification trail.</p>
</div>
<section id="statement" class="level2">
<h2 class="anchored" data-anchor-id="statement">Statement</h2>
<p>No neutral field-wide benchmark exists that compares baseline connection, CNMA, component PAIC, reference prediction, dose-response models, class effects and partial identification under shared disconnected-network data-generating mechanisms, with public seeds, versioned expected outputs and analytic-truth unit tests. Package-local infrastructure of that kind does exist: at commit 9d150e9 cpaic, an unreleased development package on GitHub that is not on CRAN, ships seeded disconnected-network fixtures with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests and cross-package equivalence checks against maicplus. Independent comparative simulation also exists for parts of the field: Chandler and Proskorovsky (doi:10.1002/jrsm.1759) compared four families of MAIC variance estimator across 108 scenarios, and Liu et al.&nbsp;(doi:10.1007/s40258-025-00952-1) ran a 729-scenario full-factorial comparison of unanchored MAIC against naive indirect comparison, neither promoting a method of its own. What is missing is the neutral, maintained, cross-package suite that any implementation can be run against.</p>
</section>
<section id="why-it-is-open" class="level2">
<h2 class="anchored" data-anchor-id="why-it-is-open">Why it is open</h2>
<p>Cross-package validation needs an agreed estimand and input format, neither of which exists, so outside a single package’s own fixtures there is nothing for expected outputs to be expected against. The independent simulation studies that do exist each answer one question and were not built to be re-run by others, so they are evidence rather than infrastructure: no seeds, manifests or reference implementations survive for the next comparison. The mechanisms that would actually discriminate between bridges, namely bridge violation, component drift, unmeasured modifiers and design differences, are still rarely simulated by anyone. Benchmarks are maintenance work with no publication reward and need cross-group coordination nobody owns, so discrepancies surface only in appraisals, where they are attributed to analyst choice rather than to software behavior.</p>
</section>
<section id="what-has-been-tried" class="level2">
<h2 class="anchored" data-anchor-id="what-has-been-tried">What has been tried</h2>
<div class="table-scroll">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Work</th>
<th>What it contributes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://github.com/choxos/cpaic">cpaic, unreleased development package on GitHub (not on CRAN), commit 9d150e9</a></td>
<td>provides seeded disconnected-network data with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests and cross-package equivalence tests against maicplus; package-local validation infrastructure that partially resolves the analytic-truth half of the claim but does not replace an independent benchmark</td>
</tr>
<tr class="even">
<td><a href="https://doi.org/10.1002/jrsm.1759">Chandler and Proskorovsky 2024, Uncertain about uncertainty in matching-adjusted indirect comparisons? A simulation study to compare methods for variance estimation, Res Synth Methods 15(6):1094-1110</a></td>
<td>compares four families of MAIC variance estimator across 108 anchored and unanchored scenarios for binary and time-to-event outcomes, with no method of its own to promote; author-neutral comparative evidence for one part of the field, but not re-runnable infrastructure</td>
</tr>
<tr class="odd">
<td><a href="https://doi.org/10.1007/s40258-025-00952-1">Liu et al.&nbsp;2025, Is the Use of Unanchored Matching-Adjusted Indirect Comparison Always Superior to Naive Indirect Comparison on Survival Outcomes? A Simulation Study</a></td>
<td>runs a 729-scenario three-level full factorial over IPD and aggregate sample size, covariate strength, correlation, overlap and effect size, identifying where unanchored MAIC is more biased than naive indirect comparison; again author-neutral evidence rather than a maintained benchmark</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="probable-solution-or-research-direction" class="level2">
<h2 class="anchored" data-anchor-id="probable-solution-or-research-direction">Probable solution or research direction</h2>
<p>Generalize what already exists rather than starting over: promote cpaic’s seeded known-truth fixtures and cross-package equivalence tests into a package-independent repository, and re-express the published author-neutral simulations as re-runnable scenarios with seeds and manifests. Add the adversarial data-generating mechanisms nobody currently simulates, including bridge violation, component drift, unmeasured modifiers and design difference, and declare an estimand and decision-relevant performance measures for each. Ship versioned expected outputs, analytic-truth unit tests and reference implementations with containerized workflows so any ITC or PAIC package can be run against them and discrepancies are attributable to software rather than to analyst choice.</p>
</section>
<section id="verification" class="level2">
<h2 class="anchored" data-anchor-id="verification">Verification</h2>
<div class="verification-trail">
<p><strong>Verdict.</strong> Partially addressed. Part of this problem is addressed by existing work; the entry names which part.</p>
<p><strong>The source titled this.</strong> “No neutral benchmark suite or analytic-truth tests for PAIC code” The title says analytic-truth tests do not exist, but seeded known-truth fixtures, analytic and non-estimability tests and cross-package equivalence checks were found.</p>
<p><strong>The source said.</strong> “There is no open benchmark suite for ITC, PAIC, disconnected-network, component and QBA methods with synthetic and real exemplars, public seeds, expected outputs, analytic-truth unit tests and cross-package validation, and no shared set of disconnected-network data-generating mechanisms under which baseline connection, CNMA, cpaic, reference prediction, dose-response models, class effects and partial identification can be compared. The report argues such a neutral comparison is a publication in its own right and may have more practical influence than another estimator paper.”</p>
<p><strong>What was wrong with it.</strong> The source claimed PAIC software is not routinely unit tested against analytic truth and that no benchmark datasets or cross-package tests exist; GPT-5.6 Sol found seeded known-truth fixtures, analytic and deliberate non-estimability tests and cross-package equivalence checks already in cpaic at commit 9d150e9, and the literature auditor rejected the premise that comparative evidence comes mostly from the authors of the method being promoted, naming two author-neutral simulation studies (doi:10.1002/jrsm.1759, doi:10.1007/s40258-025-00952-1). The claim was unattributed in the source and is now sourced; the field-wide benchmark gap survives.</p>
<p><strong>Dissent.</strong> literature dissented (open): Source-document checks pass exactly: line 2147 rates ‘Public adversarial benchmark and empirical bridge-deletion suite’ Impact 5, Novelty 3, Tractability 5, so the ‘tractability 5 out of 5’ figure is right; line 2233 states verbatim that the paper ‘may have more practical influence than another estimator paper because the field lacks trusted comparative benchmarks and has almost no reference-grade QBA software for limited-AgD unanchored PAIC’; line 1165 matches the disconnected-network benchmark claim. No maintained neutral suite with public seeds, versioned expected outputs and analytic-truth unit tests exists, so the core claim stands. The caveat is the why_open assertion that comparative evidence ‘comes mostly from simulations run by the authors of the method being promoted’. Two counterexamples: Chandler &amp; Proskorovsky (2024) ran 108 scenarios comparing four MAIC variance families with no method to promote, and Liu et al.&nbsp;(2025) ran a 729-scenario full-factorial MAIC versus naive comparison. Wigle &amp; Beliveau (2022) likewise report the first simulation comparison of CNMA models. codex dissented (overstated): The inspected sources do not contain a neutral field-wide suite comparing every named method under common disconnected-network data-generating mechanisms, so the central benchmark problem remains. However, C2, C4, and C6 are too categorical: cpaic already contains a seeded disconnected-network fixture with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests, and cross-package equivalence checks. C5 is technically correct. C8 is defensible only for the full all-method comparison. C7 is a QBA software-coverage claim rather than a mathematical result. C9 is a prediction, C10 merely reports the agenda’s own rating, and C11 is an unquantified ecosystem judgment. Existing package-local tests partially solve implementation verification but do not replace an independent benchmark.</p>
<dl>
<dt>Literature and prior-art check</dt>
<dd>
<strong>open / supported-with-caveat.</strong> Source-document checks pass exactly: line 2147 rates ‘Public adversarial benchmark and empirical bridge-deletion suite’ Impact 5, Novelty 3, Tractability 5, so the ‘tractability 5 out of 5’ figure is right; line 2233 states verbatim that the paper ‘may have more practical influence than another estimator paper because the field lacks trusted comparative benchmarks and has almost no reference-grade QBA software for limited-AgD unanchored PAIC’; line 1165 matches the disconnected-network benchmark claim. No maintained neutral suite with public seeds, versioned expected outputs and analytic-truth unit tests exists, so the core claim stands. The caveat is the why_open assertion that comparative evidence ‘comes mostly from simulations run by the authors of the method being promoted’. Two counterexamples: Chandler &amp; Proskorovsky (2024) ran 108 scenarios comparing four MAIC variance families with no method to promote, and Liu et al.&nbsp;(2025) ran a 729-scenario full-factorial MAIC versus naive comparison. Wigle &amp; Beliveau (2022) likewise report the first simulation comparison of CNMA models.
</dd>
<dt>GPT-5.6 Sol, technical and source-code lens</dt>
<dd>
<strong>partially-solved / overstated.</strong> The inspected sources do not contain a neutral field-wide suite comparing every named method under common disconnected-network data-generating mechanisms, so the central benchmark problem remains. However, C2, C4, and C6 are too categorical: cpaic already contains a seeded disconnected-network fixture with known truth, analytic estimability and likelihood tests, deliberate non-estimability tests, multi-arm tests, and cross-package equivalence checks. C5 is technically correct. C8 is defensible only for the full all-method comparison. C7 is a QBA software-coverage claim rather than a mathematical result. C9 is a prediction, C10 merely reports the agenda’s own rating, and C11 is an unquantified ecosystem judgment. Existing package-local tests partially solve implementation verification but do not replace an independent benchmark. Cites choxos/cpaic@9d150e9cad88f2e6fbcd94dbb92c3dee3b7c2dca: Provides seeded disconnected-network known-truth data, analytic estimability and likelihood tests, multi-arm tests, and cross-package equivalence tests, partially resolving the claimed absence of analytic-truth and validation infrastructure..
</dd>
<dt>Decision path</dt>
<dd>
<code>R3:partially-solved(n=1) → R9:substantiated-single-overstatement:codex</code>
</dd>
</dl>
</div>
</section>
<section id="how-the-evidence-falls-in-time" class="level2">
<h2 class="anchored" data-anchor-id="how-the-evidence-falls-in-time">How the evidence falls in time</h2>
<p>1 paper in the reviewed corpus bears on this problem, published 2026. Every paper found here asserts the problem is open; none reports progress.</p>
<div class="table-scroll">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Says</th>
<th>Paper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026</td>
<td>confirms it is open</td>
<td>Network meta-analysis with dose-response relationships.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="related-problems" class="level2">
<h2 class="anchored" data-anchor-id="related-problems">Related problems</h2>
<div class="related-links">
<ul>
<li><a href="../problems/CMU-07-published-paic-analyses-do-not-record-the-choices-that-drive.html">CMU-07 — Published PAIC analyses do not record the choices that drive them</a></li>
<li><a href="../problems/CMU-08-no-cross-package-benchmark-or-reference-pipeline-for-itc-sof.html">CMU-08 — No cross-package benchmark or reference pipeline for ITC software</a></li>
<li><a href="../problems/SFW-17-no-end-to-end-error-propagation-study-for-automated-synthesi.html">SFW-17 — No end-to-end error propagation study for automated synthesis pipelines</a></li>
</ul>
</div>
</section>
<section id="source" class="level2">
<h2 class="anchored" data-anchor-id="source">Source</h2>
<p>Derived from A:L167, A:L220, C:L214-215, C:L258, C:L1165, C:L2147, C:L2229-2233, C:L2236-2240, C:L2493 of the reviewed corpus.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/choxos\.github\.io\/ITC-open-problems\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Ahmad Sofi-Mahmudi</p>
</div>   
    <div class="nav-footer-center">
<p>Every entry carries a verification verdict. See <a href="../methods.html">How this was verified</a>.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/choxos/ITC-open-problems/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/choxos/ITC-open-problems">Source</a></p>
</div>
  </div>
</footer>




</body></html>