## Probe: bias against native targets, reversal rate, correlation of the two
## sponsors' estimates, unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(5)
pick <- g[g$sep == 1 & g$beta == 0.4 & g$sizes == "equal" & g$sets == "common", ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  r <- replicate(300, fit_all(cc, draw(cc))[, "est"])
  data.frame(position = cc$position, tA = th[["F_B"]], tB = th[["F_A"]],
             biasA = mean(r["sponsorA", ]) - th[["F_B"]], biasB = mean(r["sponsorB", ]) - th[["F_A"]],
             biasD = mean(r["transportD", ]) - th[["F_D"]], biasAvg = mean(r["average", ]) - th[["F_D"]],
             reversal = mean(sign(r["sponsorA", ]) != sign(r["sponsorB", ])),
             corr = stats::cor(r["sponsorA", ], r["sponsorB", ]))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# EST-06 probes", "", "Generated by `R/01-probes.R`. Separation 1, beta 0.4, equal sizes, common sets, 300 replicates.", "",
  "| position | truth, sponsor A (F_B) | truth, sponsor B (F_A) | bias A | bias B | bias transport-to-F_D | bias average vs F_D | P(reversal) | corr(A, B) |",
  "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.3f | %.3f | %.4f | %.4f | %.4f | %.4f | %.3f | %.3f |", rows$position, rows$tA, rows$tB,
          rows$biasA, rows$biasB, rows$biasD, rows$biasAvg, rows$reversal, rows$corr), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
