## Probe: bias, control-test flag rate and coverage of naive and calibrated contrasts, 300 replicates.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; tr <- truth(cc); r <- t(replicate(300, fit_all(draw(cc))))
  data.frame(g_n = cc$g_n, beta = cc$beta, shift = cc$shift, bias_naive = mean(r[, 1]) - tr, bias_cal = mean(r[, 5]) - tr,
             control_flag = mean(abs(r[, 3] / r[, 4]) > 1.96), cov_naive = mean(abs(r[, 1] - tr) <= 1.96 * r[, 2]), cov_cal = mean(abs(r[, 5] - tr) <= 1.96 * r[, 6])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(g))
md <- c("# IDN-09 probes", "", "Generated by `R/01-probes.R`, 300 replicates per cell.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
