## Probe: pooled interaction, selection, the two consistency checks and target bias; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(which(g$M == 4 & g$loop == 0), function(i) { cc <- g[i, ]; r <- t(replicate(400, fit_all(cc, draw(cc)))); tr <- truth(cc)
  data.frame(scen = cc$scen, sdx = cc$sdx, bC = mean(r[, "bC"]), se_bC = mean(r[, "se_bC"]), select = mean(r[, "p_int"] < ALPHA),
             int_cons = mean(r[, "p_int_cons"] < ALPHA), eff_cons = mean(r[, "p_eff_cons"] < ALPHA), bias_sel = mean(r[, "est_sel"]) - tr,
             cov_sel = mean(abs(r[, "est_sel"] - tr) <= 1.96 * r[, "se_sel"])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (400 * nrow(rows))
md <- c("# COV-10 probes", "", "Generated by `R/01-probes.R`. Four studies per comparison, no effect inconsistency, 400 replicates.", "",
  "| scenario | covariate SD | pooled b_C | its SE | modifier selected | interaction-consistency flag | effect-consistency flag | target bias after selection | coverage |",
  "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %.1f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f |", rows$scen, rows$sdx, rows$bC, rows$se_bC, rows$select, rows$int_cons, rows$eff_cons, rows$bias_sel, rows$cov_sel), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
