## P2: the shift at which a given fraction of source samples is infeasible, per
## dimension. P4: unit cost. Writes results/probes.md and results/shifts.csv.
source("R/00-model.R")
set.seed(3)
qs <- c(q10 = 0.1, q30 = 0.3, q50 = 0.5, q70 = 0.7, q90 = 0.9)
sh <- do.call(rbind, lapply(LEVELS$dim, function(d) {
  grid <- seq(1, if (d == 3) 4.5 else 3, by = 0.1)
  pinf <- vapply(grid, function(s) mean(replicate(150, !lp_feasible(
    matrix(stats::rnorm(2 * N_ARM * d), ncol = d), s * unit_dir(d)))), 0)
  pm <- stats::isoreg(grid, pinf)$yf
  data.frame(dim = d, shift = names(qs),
             s = vapply(qs, function(q) grid[which.min(abs(pm - q))], 0), q = qs)
}))
write.csv(sh, "results/shifts.csv", row.names = FALSE)
g <- build_grid()
cc <- g[g$dim == 8 & g$shift == "q50" & g$em == 0.5, ][1, ]
s <- sh$s[sh$dim == 8 & sh$shift == "q50"]; th <- truth(cc, s)
t0 <- proc.time()[["elapsed"]]
r <- t(replicate(100, one_rep(cc, s, th)))
sec <- (proc.time()[["elapsed"]] - t0) / 100
md <- c("# OVL-02 probes", "", "Generated by `R/01-probes.R`.", "",
  "## P2: shift along the equal-weight direction giving each infeasibility fraction (150 samples per grid point, isotonic fit)", "",
  "| dimension | level | shift | target infeasible fraction |", "|---:|---|---:|---:|",
  sprintf("| %d | %s | %.1f | %.1f |", sh$dim, sh$shift, sh$s, sh$q), "",
  "## Pilot at dimension 8, level q50, modification 0.5 (100 replicates)", "",
  sprintf("Infeasible %.2f. Residual imbalance, feasible: max %.2e; infeasible: min %.2e. Optimizer convergence code 0 in %.0f%% of infeasible replicates. ESS median, feasible %.1f, infeasible %.1f.",
          mean(r[, "feasible"] == 0), max(r[r[, "feasible"] == 1, "resid"]), min(r[r[, "feasible"] == 0, "resid"]),
          100 * mean(r[r[, "feasible"] == 0, "conv"] == 0), stats::median(r[r[, "feasible"] == 1, "ess"]),
          stats::median(r[r[, "feasible"] == 0, "ess"])), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
