## Probes before registration: the algebra against simulation in four cells, and
## unit cost. Writes results/probes.md.   Rscript R/01-probes.R

source("R/00-model.R")
g <- build_grid()
pick <- g[g$kappa == "0.2" & g$gu == 0.5 & g$beta == BETA, ]
set.seed(7)
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]
  r <- replicate(300, { f <- fit_all(draw(cc))
    sapply(f, function(z) z[["est"]]) - truth(cc) })
  p <- predicted(cc)
  data.frame(corr = cc$corr, method = rownames(r), bias = rowMeans(r),
             mcse = apply(r, 1, stats::sd) / sqrt(ncol(r)),
             predicted = c(unadjusted = NA, pooled = p[["pooled"]],
                           separate = p[["separate"]], two_stage = p[["pooled"]])[rownames(r)])
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# MOD-16 probes", "", "Generated by `R/01-probes.R`.", "",
  "## Algebra against simulation (300 replicates; kappa 0.2, gu 0.5, modification 0.3)", "",
  "| correlation | method | bias | MCSE | predicted |", "|---|---|---:|---:|---:|",
  sprintf("| %s | %s | %.4f | %.4f | %s |", rows$corr, rows$method, rows$bias, rows$mcse,
          ifelse(is.na(rows$predicted), "", sprintf("%.4f", rows$predicted))), "",
  "## Unit cost", "",
  sprintf("%.4f s per replicate, all methods; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
dir.create("results", showWarnings = FALSE)
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
