## Probe: each method's bias in the cells that separate the mechanisms; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(6)
pick <- g[g$rate == 0.3, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  r <- do.call(rbind, lapply(1:100, function(k) fit_all(draw(cc))))
  a <- aggregate(est ~ method, r, function(x) mean(x) - th)
  data.frame(mech = cc$mech, bu = cc$bu, method = a$method, bias = a$est,
             mcse = aggregate(est ~ method, r, function(x) stats::sd(x) / sqrt(length(x)))$est)
}))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * nrow(pick))
w <- reshape(transform(rows, v = sprintf("%.3f (%.3f)", bias, mcse))[, c("mech", "bu", "method", "v")],
             idvar = c("mech", "bu"), timevar = "method", direction = "wide")
names(w) <- sub("^v\\.", "", names(w))
md <- c("# MIS-01 probes", "", "Generated by `R/01-probes.R`. Missingness 30%, 100 replicates; bias (MCSE).", "",
  paste("|", paste(names(w), collapse = " | "), "|"), paste(rep("|---", ncol(w)), collapse = ""), "|" ,
  apply(w, 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
md <- md[md != "|"]
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
