## Probe: bias, plug-in coverage and widening ratio at the three percentiles; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- t(replicate(20, fit_all(cc, draw(cc)))); e <- sweep(r[, 1:3], 2, truth())
  data.frame(n_p = cc$n_p, drift = cc$drift, pct = Q, bias = colMeans(e), cov_plug = colMeans(abs(e) <= 1.96 * r[, 4:6]), widening = colMeans(r[, 7:9] / r[, 4:6])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (20 * nrow(g))
md <- c("# MOD-18 probes", "", "Generated by `R/01-probes.R`, 20 replicates per cell.", "",
  "| cohort size | calibration drift | risk percentile | bias | plug-in coverage | propagated / plug-in SE |", "|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.1f | %.1f | %.3f | %.2f | %.3f |", rows$n_p, rows$drift, rows$pct, rows$bias, rows$cov_plug, rows$widening), "",
  sprintf("Unit cost %.2f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
