## Probe: truths, bias by cell for each estimator, diagnostics' distributions, cost.
source("R/00-model.R")
g <- build_grid(); g$truth <- sapply(seq_len(nrow(g)), function(i) truth(g[i, ])); g$truth_r <- sapply(seq_len(nrow(g)), function(i) truth_restricted(g[i, ]))
set.seed(3); t0 <- proc.time()[["elapsed"]]
pick <- g[g$b == 0.6, ]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) { cc <- pick[i, ]
  r <- t(replicate(100, fit_all(draw(cc))))
  data.frame(c_trunc = cc$c_trunc, align = cc$align, shape = cc$shape, truth = cc$truth,
             bias_maic = mean(r[, "maic_est"]) - cc$truth, bias_gc = mean(r[, "gc_est"]) - cc$truth,
             bias_trim_r = mean(r[, "trim_est"]) - cc$truth_r, sd_gc = stats::sd(r[, "gc_est"]), sd_maic = stats::sd(r[, "maic_est"]),
             ess = mean(r[, "ess_frac"]), unsup = mean(r[, "unsup_mass"]), score = mean(r[, "align_score"])) }))
sec <- (proc.time()[["elapsed"]] - t0) / (100 * nrow(pick))
md <- c("# OVL-01 probes", "", "Generated by `R/01-probes.R`. Modification strength 0.6, 100 replicates.", "",
  "| truncation | alignment | shape | truth | bias MAIC | bias G-comp | bias trimmed vs restricted | SD G-comp | SD MAIC | ESS/n | unsupported mass | alignment score |",
  "|---:|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
  sprintf("| %s | %s | %s | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f |", rows$c_trunc, rows$align, rows$shape, rows$truth,
          rows$bias_maic, rows$bias_gc, rows$bias_trim_r, rows$sd_gc, rows$sd_maic, rows$ess, rows$unsup, rows$score), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
