## Probe: bias by method against the prediction in four cells; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(15)
pick <- g[g$d2 == 0 & g$median_A == 8 & g$effect == 3, ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  r <- t(replicate(200, fit_all(cc)))
  data.frame(d1 = cc$d1, predicted = predicted_bias(cc), naive = mean(r[, "naive"]) - th,
             midpoint = mean(r[, "midpoint"]) - th, interval = mean(r[, "interval"]) - th,
             mcse = stats::sd(r[, "naive"]) / sqrt(nrow(r)))
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(pick))
md <- c("# OUT-14 probes", "", "Generated by `R/01-probes.R`. d2 = 0, A median 8 months, B median 11, 200 replicates.", "",
  "| d1 | predicted naive bias | naive | midpoint | interval-censored | MCSE (naive) |", "|---:|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.3f | %.3f | %.3f | %.3f | %.3f |", rows$d1, rows$predicted, rows$naive, rows$midpoint, rows$interval, rows$mcse), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
