## Probe: coverage by method, study count and heterogeneity, 300 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- do.call(rbind, replicate(300, fit_all(cc, draw(cc)), simplify = FALSE))
  r$cov <- abs(r$est - truth()) <= r$crit * r$se; a <- tapply(r$cov, r$method, mean); data.frame(K = cc$K, tau = cc$tau, t(a)) }))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(g))
md <- c("# HET-10 probes", "", "Generated by `R/01-probes.R`. Coverage, 300 replicates per cell.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---:", ncol(rows)), collapse = ""),
  apply(round(rows, 3), 1, function(r) paste("|", paste(r, collapse = " | "), "|")), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md")
