## Probe: bias of each method by assay scenario and modification, 150 replicates; cost.
source("R/00-model.R")
g <- build_grid(); set.seed(1); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; r <- t(replicate(150, fit_all(cc, draw(cc))))
  data.frame(assay = cc$assay, b = cc$b, truth = truth(cc), t(colMeans(r) - truth(cc))) }))
sec <- (proc.time()[["elapsed"]] - t0) / (150 * nrow(g))
md <- c("# QBA-06 probes", "", "Generated by `R/01-probes.R`, 150 replicates per cell. Bias of the target log odds ratio.", "",
  paste("|", paste(names(rows), collapse = " | "), "|"), paste(rep("|---", ncol(rows)), collapse = ""),
  apply(rows, 1, function(r) paste("|", paste(c(r[1], sprintf("%.3f", as.numeric(r[-1]))), collapse = " | "), "|")), "",
  sprintf("Unit cost %.3f s per replicate; %d cells at %d replicates is %.2f core-hours.", sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
