## Probe: each method's bias and the representation difference in the four
## cells where DESIGN.md and the algebra disagree most, plus unit cost.
source("R/00-model.R")
g <- build_grid()
pick <- g[g$shift == 1 & g$b == 0.4, ]
set.seed(11); t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  r <- replicate(300, fit_all(cc, draw(cc)))
  e <- r - th
  df <- data.frame(design = cc$design, beta = cc$beta, method = rownames(r),
                   bias = rowMeans(e), mcse = apply(e, 1, stats::sd) / sqrt(ncol(e)))
  for (m in c("naive", "maic", "gcomp")) {
    dd <- r[paste0(m, "_end"), ] - r[paste0(m, "_chg"), ]
    df <- rbind(df, data.frame(design = cc$design, beta = cc$beta,
      method = paste0(m, " end-chg"), bias = mean(dd), mcse = stats::sd(dd) / sqrt(length(dd))))
  }
  df
}))
sec <- (proc.time()[["elapsed"]] - t0) / (300 * nrow(pick))
md <- c("# OUT-06 probes", "", "Generated by `R/01-probes.R`. Shift 1, b = 0.4, 300 replicates.", "",
  "| design | beta | quantity | mean | MCSE |", "|---|---:|---|---:|---:|",
  sprintf("| %s | %.1f | %s | %.4f | %.4f |", rows$design, rows$beta, rows$method, rows$bias, rows$mcse), "",
  sprintf("Unit cost %.4f s per replicate; %d cells at %d replicates is %.2f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
