## P1 grid and weight feasibility (covariates only), P2 null control on a few
## half splits, P4 positive control on the shift units, P5 unit cost.
## No main-unit discrepancy is computed.
## Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); g <- build_grid(); set.seed(1)
out <- c("# Probes", "", "Generated by `R/01-probes.R`. No main-unit discrepancy on the real outcomes is computed here.", "")
p1 <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { u <- g[i, ]; dd <- unit_data(u); x <- xset(u); xa <- as.matrix(dd$sa[, x]); tg <- mask(dd$dm, u)$xbar[x]
  w <- maic_w(xa, tg); data.frame(net = u$net, kind = u$kind, ess = sum(w)^2 / sum(w^2) / length(w), bal = max(abs(colSums(w * xa) / sum(w) - tg) / apply(xa, 2, stats::sd)),
                                  sep = sqrt(mean(((colMeans(xa) - tg) / apply(xa, 2, stats::sd))^2))) }))
q <- function(v) paste(sprintf("%.3f", stats::quantile(v, c(0, 0.5, 1))), collapse = " / ")
out <- c(out, "## P1 grid and weight feasibility (covariates only)", "", sprintf("- %d units: %s", nrow(g), paste(sprintf("%s %d", names(table(interaction(g$net, g$kind))), table(interaction(g$net, g$kind))), collapse = ", ")),
  sprintf("- %s: ESS share min / median / max %s; separation %s; worst imbalance after weighting %.1e", unique(p1$net), vapply(unique(p1$net), function(n) q(p1$ess[p1$net == n]), ""),
          vapply(unique(p1$net), function(n) q(p1$sep[p1$net == n]), ""), vapply(unique(p1$net), function(n) max(p1$bal[p1$net == n]), 0)), "")
p2 <- do.call(rbind, lapply(seq_len(nrow(NULL_SET)), function(k) t(replicate(3, null_split(k, n_boot = 40)))))
out <- c(out, "## P2 null control (3 half splits per trial, 40 bootstrap draws)", "",
  sprintf("- %d analyses: |z| > 1.96 naive %d, MAIC %d; max |z| naive %.2f, MAIC %.2f", nrow(p2), sum(abs(p2[, 1]) > 1.96), sum(abs(p2[, 2]) > 1.96), max(abs(p2[, 1])), max(abs(p2[, 2]))), "")
## P4: positive control on the real outcomes (shift units only), 100 bootstrap draws.
p4 <- lapply(which(g$kind == "shift"), function(i) one_unit(g[i, ], n_boot = 100))
zz <- function(r, s) r$point[[s]] / rse(r$boot[, s])
out <- c(out, "## P4 positive control on the real outcomes (shift units, 100 bootstrap draws)", "",
  sprintf("- unit %d (%s, S %s, M %s subgroup, n %d): naive z %.2f, MAIC z %.2f", vapply(p4, function(r) r$unit$unit, 0L), vapply(p4, function(r) r$unit$net, ""),
          vapply(p4, function(r) r$unit$S, ""), vapply(p4, function(r) r$unit$M, ""), vapply(p4, `[[`, 0L, "nM"), vapply(p4, zz, 0, "d_naive"), vapply(p4, zz, 0, "d_maic")), "")
tm <- vapply(c(which(g$net == "pso")[1], which(g$net == "ndmm")[1]), function(i) { u <- g[i, ]; dd <- unit_data(u); system.time(for (k in 1:10) stats_one(rs(dd$sa), rs(dd$dm), u))[["user.self"]] / 10 }, 0)
nu <- table(g$net)[c("pso", "ndmm")]; nn <- table(NULL_SET$net)[c("pso", "ndmm")]
tot <- sum(nu * tm) * (N_BOOT + 1) + sum(nn * tm) * R_NULL * (B_NULL + 1)
out <- c(out, "## P5 unit cost", "", sprintf("- CPU per evaluation: pso %.3f s, ndmm %.3f s (heavily loaded shared machine)", tm[1], tm[2]),
  sprintf("- registered run: %d units x %d draws plus %d x %d half splits x %d draws, about %.2f CPU hours", nrow(g), N_BOOT, nrow(NULL_SET), R_NULL, B_NULL, tot / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
