## Probe: abstention rate of each screen in valid and violated bridges; unit cost.
source("R/00-model.R")
g <- build_grid(); set.seed(19)
pick <- g[g$K == 10 & (g$drift == "none" | g$size == 0.3), ]
t0 <- proc.time()[["elapsed"]]
rows <- do.call(rbind, lapply(seq_len(nrow(pick)), function(i) {
  cc <- pick[i, ]; th <- truth(cc)
  r <- t(replicate(200, fit_all(cc, draw(cc))))
  data.frame(G = cc$G, drift = cc$drift, abst_cond = mean(r[, "p_cond"] < 0.1), abst_marg = mean(r[, "p_marg"] < 0.1),
             abst_std = mean(r[, "p_std"] < 0.1), bias_pooled = mean(r[, "pooled_cond"]) - th)
}))
sec <- (proc.time()[["elapsed"]] - t0) / (200 * nrow(pick))
md <- c("# ADJ-09 probes", "", "Generated by `R/01-probes.R`. K = 10, 200 replicates.", "",
  "| prognostic G | drift | abstain, conditional | abstain, marginal | abstain, standardized | bias of pooled conditional in gap |",
  "|---:|---|---:|---:|---:|---:|",
  sprintf("| %.1f | %s | %.3f | %.3f | %.3f | %.3f |", rows$G, rows$drift, rows$abst_cond, rows$abst_marg, rows$abst_std, rows$bias_pooled), "",
  sprintf("Unit cost %.3f s per replicate at K = 10; %d cells at %d replicates is roughly %.1f core-hours.",
          sec, nrow(g), N_SIM, nrow(g) * N_SIM * sec * 0.7 / 3600), "")
writeLines(md, "results/probes.md"); cat(md, sep = "\n")
