## Data-generating mechanism: a component network with a binary effect modifier
## whose prevalence varies across studies.
##
## Twelve two-arm randomized trials over four regimens built from two components:
## control = (0,0), A = (1,0), B = (0,1), AB = (1,1). The four trial designs are
## control:A, control:B, A:AB and B:AB, three trials each, so every comparison
## adds exactly one component and the network identifies both component effects.
##
## One binary modifier X, with study-specific prevalence p_s. Write
## z = X - p_s for the within-study deviation. The individual log rate is
##
##   eta = alpha_s + beta*z + sum_c a_c { delta_c + gammaW_c * z + q_c(p_s) }
##
## so gammaW_c is the causal within-trial interaction, identified by randomized
## contrasts inside a trial, and q_c(p_s) is an across-trial association between
## a study's case mix and its component effect. Nothing randomizes q_c: it stands
## for everything that differs between trial populations and happens to correlate
## with prevalence.
##
## The algebra that makes this the right test. A single shared interaction on the
## globally centered covariate satisfies
##
##   gamma * (X - 0.5) = gamma * (X - p_s) + gamma * (p_s - 0.5),
##
## so fitting one shared Gamma does not merely pool the two sources of
## information: it *imposes* gammaW = gammaB. The study measures what that costs.
##
## Aggregate arms are generated by exact integration of the individual model over
## the two-point covariate distribution, not by a regression on p_s. That matters:
## ML-NMR integrates precisely to avoid plug-in aggregation bias, so generating
## the aggregate data any other way would test a method nobody uses.

## Truth patterns.
##
## gamma_W is the causal within-trial interaction; gamma_B is the across-trial
## association between a study's case mix and its component effect. The rho
## patterns set gamma_B = rho * gamma_W, so rho = 1 is the case in which a single
## shared Gamma is exactly correct and rho = 0 is the case in which the
## across-trial association is absent. `nonlinear` makes every linear model
## wrong.
GW   <- c(A = 0.405465, B = -0.356675)      # log(1.5), log(0.70)
ZERO <- c(A = 0, B = 0)

TRUTH <- list(
  rho1          = list(gW = GW,   gB =  1.0 * GW, q = NULL),
  `rho0.5`      = list(gW = GW,   gB =  0.5 * GW, q = NULL),
  rho0          = list(gW = GW,   gB =  ZERO,     q = NULL),
  `rho-0.5`     = list(gW = GW,   gB = -0.5 * GW, q = NULL),
  `rho-1`       = list(gW = GW,   gB = -1.0 * GW, q = NULL),
  null          = list(gW = ZERO, gB =  ZERO,     q = NULL),
  `between-only`= list(gW = ZERO, gB =  GW,       q = NULL),
  ## Across-trial association quadratic in prevalence, so its linear projection
  ## is near zero and a linear split model is misspecified too. Only gamma_W is
  ## assessed here: the review established that the implied pseudo-true gamma_B
  ## is a likelihood-weighted projection over each component's own informative
  ## trials, not the unweighted zero the design assumed, so gamma_B coverage
  ## under this pattern would be assessed against the wrong number.
  nonlinear     = list(gW = GW,   gB = ZERO,
    q = function(p, M) c(A = 1.5 * ((p - 0.5)^2 - M),
                         B = -1.2 * ((p - 0.5)^2 - M)))
)

BETA   <- 0.405465        # prognostic log rate ratio for X = 1 vs 0, i.e. 1.50
DELTA  <- c(A = -0.356675, B = -0.287682)   # log(0.70), log(0.75)
BASE_RATE <- 0.30

PREVALENCE <- list(
  narrow = c(0.35, 0.38, 0.40, 0.42, 0.45, 0.48, 0.52, 0.55, 0.58, 0.60, 0.62, 0.65),
  wide   = c(0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85)
)

## Regimen component indicators.
REGIMEN <- rbind(control = c(A = 0, B = 0), A = c(1, 0),
                 B = c(0, 1), AB = c(1, 1))
## Two network structures, four designs each, three trials per design.
##
## `isolating`: every contrast adds exactly one component, so each interaction is
## recoverable from a directly component-isolating comparison.
##
## `bundled`: control:AB moves both components at once and A:B removes one while
## adding the other, so contrasts are aliased across components and the component
## decomposition has to do real work. Both structures still identify both
## component main effects: control:A gives delta_A, and control:AB gives
## delta_A + delta_B and hence delta_B.
NETWORKS <- list(
  isolating = list(c("control", "A"), c("control", "B"),
                   c("A", "AB"), c("B", "AB")),
  bundled   = list(c("control", "AB"), c("A", "B"),
                   c("control", "A"), c("B", "AB"))
)

## Designs in which NO arm contains component B, used by the `no-B-ipd` scheme.
##
## Selecting by which component a contrast *changes* does not work here, and the
## reason is worth stating. Stage 1 identifies gamma_W from the covariate slope
## within an arm, which is beta + sum_c a_c gamma_W,c, not from the treatment
## contrast. So a single arm containing component B identifies gamma_W,B once
## beta is known, even if no contrast in that trial changes B. To leave a
## component genuinely without within-trial information, individual data must
## come only from trials in which that component never appears.
no_B_designs <- function(structure) {
  vapply(NETWORKS[[structure]], function(d)
    all(REGIMEN[d, "B"] == 0), logical(1))
}

## Assign the 12 prevalences to the 12 trials so that every design receives one
## value from each tertile. Without that constraint a replicate can hand all the
## low-prevalence trials to one design, which confounds the design structure with
## the covariate spread the study is trying to vary.
assign_prevalence <- function(prev) {
  o <- sort(prev)
  tert <- split(o, rep(1:3, each = 4))
  out <- matrix(NA_real_, 4, 3)               # design x replicate-within-design
  for (k in 1:3) out[, k] <- sample(tert[[k]])
  as.vector(out)                              # design varies fastest
}

## Build the 12-trial skeleton for one replicate.
make_network <- function(prev_set) {
  p <- assign_prevalence(PREVALENCE[[prev_set]])
  data.frame(
    study  = 1:12,
    design = rep(1:4, times = 3),
    p      = p,
    stringsAsFactors = FALSE
  )
}

## Which studies contribute individual data.
##
## `low` selects the lowest-prevalence trial in every design, which is the case
## where IPD availability is correlated with case mix rather than independent of
## it. That is the realistic worry: trials with individual data available are
## rarely a random sample of the network.
choose_ipd <- function(net, scheme, structure) {
  by_design <- split(net$study, net$design)
  switch(scheme,
    all  = net$study,
    six  = unlist(lapply(by_design, function(s) sample(s, 2))),
    four = unlist(lapply(by_design, function(s) sample(s, 1))),
    `four-low` = unlist(lapply(by_design,
                               function(s) s[which.min(net$p[s])])),
    ## Individual data only where the contrast moves component A, so no trial
    ## anywhere supplies a within-trial contrast for component B and gamma_W,B
    ## rests entirely on aggregate variation. This is the case IDN-06 describes
    ## and the one in which a method should decline to report rather than quietly
    ## supply the estimate from an ecological gradient.
    `no-B-ipd` = net$study[net$design %in% which(no_B_designs(structure))],
    stop("unknown IPD scheme: ", scheme))
}

## Linear predictor contribution excluding the study intercept.
##
## `x` is the covariate value, `a` the component indicator vector for the arm's
## regimen, `p` the study prevalence.
lp_rest <- function(x, a, p, gW, gB, qfun, M) {
  z <- x - p
  q <- if (is.null(qfun)) c(A = gB[["A"]] * (p - 0.5), B = gB[["B"]] * (p - 0.5))
       else qfun(p, M)
  BETA * z +
    a[["A"]] * (DELTA[["A"]] + gW[["A"]] * z + q[["A"]]) +
    a[["B"]] * (DELTA[["B"]] + gW[["B"]] * z + q[["B"]])
}

## Generate one replicate.
##
## Returns cell-level sufficient statistics, which lose nothing: X is binary and
## treatment is constant within an arm, so an arm has only two covariate cells.
## For an IPD arm both cell totals are observed; for an aggregate arm only their
## sum is, and that difference is the whole distinction between the two data
## types in this model.
gen_replicate <- function(n_arm, prev_set, ipd_scheme, pattern,
                          structure = "isolating") {
  tr <- TRUTH[[pattern]]
  net <- make_network(prev_set)
  M <- mean((PREVALENCE[[prev_set]] - 0.5)^2)
  ipd <- choose_ipd(net, ipd_scheme, structure)
  alpha <- log(BASE_RATE) + stats::runif(12, -0.20, 0.20)

  rows <- vector("list", 0L)
  for (s in seq_len(12)) {
    p <- net$p[s]
    n1 <- round(n_arm * p); n0 <- n_arm - n1     # stratified: exact counts
    des <- NETWORKS[[structure]][[net$design[s]]]
    for (arm in seq_along(des)) {
      reg <- des[arm]
      a <- REGIMEN[reg, ]
      r0 <- exp(alpha[s] + lp_rest(0, a, p, tr$gW, tr$gB, tr$q, M))
      r1 <- exp(alpha[s] + lp_rest(1, a, p, tr$gW, tr$gB, tr$q, M))
      is_ipd <- s %in% ipd
      if (is_ipd) {
        y0 <- stats::rpois(1, n0 * r0)
        y1 <- stats::rpois(1, n1 * r1)
      } else {
        ## The aggregate arm total is Poisson with the exactly integrated mean,
        ## which is also the exact distribution of the sum of the individual
        ## outcomes. Generating it this way keeps the two data types comparable.
        y <- stats::rpois(1, n0 * r0 + n1 * r1)
        y0 <- NA_integer_; y1 <- NA_integer_
      }
      rows[[length(rows) + 1L]] <- data.frame(
        study = s, design = net$design[s], p = p, ipd = is_ipd,
        regimen = reg, aA = a[["A"]], aB = a[["B"]],
        n0 = n0, n1 = n1,
        y0 = if (is_ipd) y0 else NA_integer_,
        y1 = if (is_ipd) y1 else NA_integer_,
        ytot = if (is_ipd) y0 + y1 else y,
        stringsAsFactors = FALSE)
    }
  }
  do.call(rbind, rows)
}

## True marginal AB versus control log rate ratio in a target population with
## Pr(X = 1) = 0.5, with the across-trial context evaluated at p = 0.5.
##
## Two-point integration, so exact.
true_marginal_AB <- function(pattern, prev_set) {
  tr <- TRUTH[[pattern]]
  M <- mean((PREVALENCE[[prev_set]] - 0.5)^2)
  rate <- function(reg) {
    a <- REGIMEN[reg, ]
    0.5 * exp(log(BASE_RATE) + lp_rest(0, a, 0.5, tr$gW, tr$gB, tr$q, M)) +
    0.5 * exp(log(BASE_RATE) + lp_rest(1, a, 0.5, tr$gW, tr$gB, tr$q, M))
  }
  log(rate("AB") / rate("control"))
}

## True within-trial interaction, the primary estimand.
true_gW <- function(pattern) TRUTH[[pattern]]$gW
