## Probes: the treatment unit's rank test (P3); closed-form single-row LOO against
## direct conditioning; one replicate per cell, timed (P2, P4); null and positive
## controls on 10 replicates; multinma's loo unit on one small fit.
## Writes results/probes.md.
source("R/00-model.R"); g <- build_grid()
out <- c("# SFW-08 probes", "", sprintf("Generated by `R/01-probes.R`; loo %s, multinma %s.", utils::packageVersion("loo"), utils::packageVersion("multinma")), "")

## P3: leave out every arm of C; is d_C still estimable?
set.seed(1); d <- draw(g[g$ipd == 6 & g$tau == 0 & g$leverage == "none", ]); Z <- design(d, "M1", 0)$Z
Zc <- Z[d$trt != "C", ]; e <- replace(numeric(ncol(Z)), 9, 1); P <- crossprod(Zc)
est <- max(abs(e %*% MASS::ginv(P) %*% P - e)) < 1e-8
out <- c(out, "## P3 treatment unit", "", sprintf("- Without every arm of C, d_C is estimable: %s (projection test on the M1 design). The treatment unit has no predictive estimand without exchangeable treatment effects.", est), "")

## Single-row closed form against direct conditioning.
ds <- design(d, "M1", 0); ps <- posterior(ds$Z, ds$P0, d$y, d$v); i <- c(1, 250, nrow(d))
dif <- max(abs(exact_point(ps, ds$Z, d$y, d$v)[i] - vapply(i, function(r) exact_group(ps, ds$Z, d$y, d$v, r), 0)))
## A singleton group's mean is its row: exact_mean must equal exact_group, and the
## E_loo route must equal loo::loo, on the aggregate arms of a one-IPD-study network.
set.seed(2); d1 <- draw(g[g$ipd == 1 & g$tau == 0 & g$leverage == "none", ]); ds1 <- design(d1, "M1", 0); ps1 <- posterior(ds1$Z, ds1$P0, d1$y, d1$v); ag <- which(d1$v < 1)
dm <- max(abs(vapply(ag, function(r) exact_mean(ps1, ds1$Z, d1$y, d1$v, r) - exact_group(ps1, ds1$Z, d1$y, d1$v, r), 0)))
th <- sweep(matrix(stats::rnorm(S_DRAWS * length(ps1$m)), S_DRAWS) %*% chol(solve(ps1$P)), 2, ps1$m, "+")
ll <- sapply(ag, function(r) stats::dnorm(d1$y[r], drop(th %*% ds1$Z[r, ]), sqrt(d1$v[r]), log = TRUE))
e1 <- loo::loo(ll, r_eff = rep(1, ncol(ll)))$pointwise[, "elpd_loo"]; w <- loo::psis(-ll, r_eff = rep(1, ncol(ll)))
e2 <- log(loo::E_loo(exp(ll), w, type = "mean", log_ratios = -ll)$value)
out <- c(out, "## Exact LOO implementation", "", sprintf("- Hat-matrix single-row LOO against direct Gaussian conditioning, three rows: largest difference %.1e.", dif),
  sprintf("- Singleton groups (aggregate arms): exact_mean against exact_group %.1e; E_loo route against loo::loo %.1e.", dm, max(abs(e1 - e2))), "")

## One replicate per cell, timed.
t0 <- proc.time()[["user.self"]]
one <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { set.seed(20 + i); z <- one_rep(g[i, ]); z$cell <- i; z }))
sec <- (proc.time()[["user.self"]] - t0) / nrow(g)
one <- merge(g, one, by = "cell"); one <- one[one$model == "M1", ]
out <- c(out, "## One replicate per cell (M1)", "", "| IPD studies | tau | leverage | unit | terms | exact elpd | PSIS elpd | max k | units k > 0.7 |", "|---:|---:|---|---|---:|---:|---:|---:|---:|",
  sprintf("| %d | %.1f | %s | %s | %d | %.2f | %.2f | %.2f | %d |", one$ipd, one$tau, one$leverage, one$unit, as.integer(one$n_terms), one$elpd_exact, one$elpd_psis, one$k_max, as.integer(one$n_bad)), "",
  sprintf("- %.2f CPU s per replicate (both models, three units); registered run %d cells x %d = %.1f CPU hours.", sec, nrow(g), N_SIM, sec * nrow(g) * N_SIM / 3600), "")

## Controls, 10 replicates.
ctl <- function(cid, u) { z <- do.call(rbind, lapply(1:10, function(k) { set.seed(900 + k); one_rep(g[cid, ]) })); z <- z[z$model == "M1" & z$unit == u, ]
  sprintf("mean |PSIS - exact| %.3f (SD %.3f), networks with k > 0.7 %.1f, units with k > 0.7 %.4f", mean(abs(z$elpd_psis - z$elpd_exact)), stats::sd(abs(z$elpd_psis - z$elpd_exact)), mean(z$k_max > 0.7), sum(z$n_bad) / sum(z$n_terms)) }
out <- c(out, "## Controls (10 replicates, M1)", "",
  paste("- Null (all IPD, tau 0, no leverage, pointwise):", ctl(which(g$ipd == 6 & g$tau == 0 & g$leverage == "none"), "pointwise")),
  paste("- Positive (1 IPD study, tau 0.3, one influential study, study unit):", ctl(which(g$ipd == 1 & g$tau == 0.3 & g$leverage == "one"), "study")), "")

## multinma's loo unit: one small ML-NMR fit (normal likelihood), 2 chains x 150 iterations.
suppressPackageStartupMessages(library(multinma)); set.seed(5); d <- draw(g[g$ipd == 3 & g$tau == 0 & g$leverage == "none", ])
ipd <- d[d$v == 1, ]; ipd$study <- paste0("S", ipd$study)
ipd$xc <- ipd$x; ag <- d[d$v < 1, ]; agd <- data.frame(study = paste0("S", ag$study), trt = ag$trt, y = ag$y, se = sqrt(ag$v), xc_mean = ag$x, xc_sd = 1, n = N_ARM)   # add_integration's first formal is x
t1 <- proc.time()
res <- tryCatch({ net <- suppressMessages(combine_network(set_ipd(ipd, study, trt, y = y), set_agd_arm(agd, study, trt, y = y, se = se, sample_size = n)))
  net <- add_integration(net, xc = distr(qnorm, xc_mean, xc_sd), n_int = 16)
  f <- suppressWarnings(nma(net, regression = ~ xc * .trt, trt_effects = "fixed", likelihood = "normal", chains = 2, iter = 150, seed = 5, refresh = 0))
  lo <- suppressWarnings(loo::loo(f)); c(n_pointwise = nrow(lo$pointwise), n_ipd = nrow(ipd), n_agd_arms = nrow(agd)) }, error = function(e) conditionMessage(e))
el <- proc.time() - t1
out <- c(out, "## multinma's loo unit (one fit, 3 of 6 studies IPD)", "",
  if (is.character(res)) paste("- failed:", res) else sprintf("- loo() pointwise terms %d = IPD patients %d + aggregate arms %d: %s.", res[["n_pointwise"]], res[["n_ipd"]], res[["n_agd_arms"]],
    res[["n_pointwise"]] == res[["n_ipd"]] + res[["n_agd_arms"]]), sprintf("- %.1f CPU s.", el[["user.self"]] + el[["sys.self"]]), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
