## P1 exact sampling components and the coverage each prior reaches in the limit
## (tau2_hat at its probability limit); P2 the published benchmark's arithmetic;
## P3 smoke replicates of every method and unit cost.
## Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); g <- build_grid(); out <- c("# Probes", "", "Generated by `R/01-probes.R`.", "")
ie <- mean(1 / E_RANGE)
out <- c(out, "## P1 sampling components, exact", "",
  sprintf("- E[1/E] over events 25 to 150: %.5f; sampling variance of D (shared arm) %.4f, SD %.3f", ie, 2 * ie, sqrt(2 * ie)),
  sprintf("- mean of se_rct^2 + se_emul^2 (both reported SEs): %.4f, so the naive subtraction removes %.4f too much", 4 * ie, 2 * ie), "")
lim <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) { cc <- g[i, ]; t2 <- cc$tau^2 + cc$sig_m^2
  est <- c(raw = t2 + 2 * ie, naive = max(0, t2 - 2 * ie), shared = t2)
  data.frame(cell = cc$cell, tau = cc$tau, sig_m = cc$sig_m, K = cc$K, t(stats::setNames(coverage(MU_B, 1.96 * sqrt(SE_NEW^2 + est), cc), names(est)))) }))
lim <- lim[lim$K == 15, ]
out <- c(out, "Limiting coverage of the new submission's bias-adjusted 95% interval (no estimation noise in mu_hat or tau2_hat):", "",
  "| tau | mismatch SD | raw | naive | shared |", "|---:|---:|---:|---:|---:|",
  sprintf("| %.1f | %.1f | %.3f | %.3f | %.3f |", lim$tau, lim$sig_m, lim$raw, lim$naive, lim$shared), "")
## P2 Gupta et al. 2025 published summary: 15 comparisons, per-trial discrepancies
## -0.229 to 1.205. Expected range of 15 standard normals, exact by integration.
d2 <- stats::integrate(function(x) 1 - stats::pnorm(x)^15 - stats::pnorm(-x)^15, -Inf, Inf)$value
sdD <- (1.205 + 0.229) / d2
out <- c(out, "## P2 arithmetic on the published benchmark", "",
  sprintf("- expected range of 15 normals %.3f; SD of D implied by the range %.3f, variance %.3f", d2, sdD, sdD^2),
  sprintf("- systematic variance if the per-comparison sampling variance is 0.01 to 0.04: %.3f to %.3f (share of var(D) %.2f to %.2f)",
          sdD^2 - 0.04, sdD^2 - 0.01, (sdD^2 - 0.04) / sdD^2, (sdD^2 - 0.01) / sdD^2),
  "- per-trial standard errors are not in this repository, so this bracket is declared, not computed", "")
## P3 smoke: 20 replicates in every cell.
t0 <- proc.time()
s <- do.call(rbind, lapply(seq_len(nrow(g)), function(i) do.call(rbind, lapply(1:20, function(k) {
  set.seed(MASTER_SEED %% 1e6 + 7919L * k + 104729L * g$cell[i]); transform(one_rep(g[i, ]), cell = g$cell[i]) }))))
tt <- proc.time() - t0; cpu <- (tt[["user.self"]] + tt[["sys.self"]]) / (20 * nrow(g))
a <- aggregate(cbind(coverage, tau2_hat) ~ cell + method, data = s, FUN = mean); a <- merge(g, a, by = "cell")
a <- a[a$method %in% METHODS, ]; a <- a[order(a$cell, match(a$method, METHODS)), ]
out <- c(out, "## P3 smoke (20 replicates per cell)", "", "| tau | mismatch SD | K | method | mean coverage | mean tau2_hat |", "|---:|---:|---:|---|---:|---:|",
  sprintf("| %.1f | %.1f | %d | %s | %.3f | %.4f |", a$tau, a$sig_m, a$K, a$method, a$coverage, a$tau2_hat), "",
  sprintf("- REML converged in %d of %d fits (DL used otherwise)", sum(s$reml_ok[s$method == "reml"]), sum(s$method == "reml")),
  sprintf("- CPU per replicate %.4f s on a shared machine at load above 500; registered run %d cells x %d replicates, about %.2f CPU-hours",
          cpu, nrow(g), N_SIM, nrow(g) * N_SIM * cpu / 3600), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
