## P1 cut census (design only), P2 bridge-true null and P3 positive control on a
## few replicates, P4 unit cost. The real cuts are not scored.
## Writes results/probes.md.   nice -n 19 Rscript R/01-probes.R
source("R/00-model.R"); set.seed(1); R_P <- 3L; cpu_tot <- 0
out <- c("# Probes", "", "Generated by `R/01-probes.R`. The real outcomes are not scored here.", "",
  "| network | studies | treatments | valid cuts | removed studies (median) | population separation (median, max) | design separation (median, max) | cuts with a zero-df side | null var z | null rejection | positive var z | CPU s per replicate |",
  "|---|---:|---:|---:|---:|---|---|---:|---|---|---|---:|")
for (n in names(NETS)) { d <- NETS[[n]]; cc <- enum_cuts(d)
  dc <- lapply(cc, function(k) apply_cut(d, k)); z0 <- mean(vapply(seq_along(cc), function(i) side_df(dc[[i]], cc[[i]]$side1) == 0 || side_df(dc[[i]], setdiff(unique(dc[[i]]$trt), cc[[i]]$side1)) == 0, TRUE))
  sepv <- function(v) { if (!v %in% SEPS[[n]]) return("NA"); st <- unique(d[, c("study", v)]); s <- vapply(seq_along(cc), function(i) { sc <- unique(dc[[i]][, c("study", v)]); side <- tapply(dc[[i]]$trt %in% cc[[i]]$side1, dc[[i]]$study, any)[sc$study]
    abs(mean(sc[[v]][side]) - mean(sc[[v]][!side])) / stats::sd(st[[v]]) }, 0); sprintf("%.2f, %.2f", stats::median(s), max(s)) }
  t0 <- proc.time()[["user.self"]]; nl <- t(replicate(R_P, cut_stats(score_cuts(simulate_net(d, n), n, cc, adjusted = FALSE), n))); cpu <- (proc.time()[["user.self"]] - t0) / R_P; cpu_tot <- cpu_tot + cpu
  ps <- t(replicate(R_P, cut_stats(score_cuts(simulate_net(d, n, GAMMA), n, cc, adjusted = FALSE), n)))
  f <- function(v) paste(sprintf("%.2f", v), collapse = ", ")
  out <- c(out, sprintf("| %s | %d | %d | %d | %g | %s | %s | %.2f | %s | %s | %s | %.1f |", n, length(unique(d$study)), length(unique(d$trt)), length(cc), stats::median(vapply(cc, `[[`, 0L, "removed")),
    sepv("pop"), sepv("des"), z0, f(nl[, "T_var"]), f(nl[, "rej"]), f(ps[, "T_var"]), cpu)) }
## af power: slopes of |e| under the bridge-true null and under the positive control.
d <- NETS$af; cc <- enum_cuts(d); R_A <- 10L
na <- t(replicate(R_A, cut_stats(score_cuts(simulate_net(d, "af"), "af", cc, adjusted = FALSE), "af")))
pa <- t(replicate(R_A, cut_stats(score_cuts(simulate_net(d, "af", GAMMA), "af", cc, adjusted = FALSE), "af")))
rng <- function(v) sprintf("median %.3f, range %.3f to %.3f", stats::median(v), min(v), max(v))
out <- c(out, "", sprintf("## af separation slopes, %d null and %d positive-control replicates", R_A, R_A), "",
  sprintf("- %s: null %s; positive control %s; positive replicates above the null maximum %d of %d", c("T_pop", "T_des", "T_var"),
          vapply(c("T_pop", "T_des", "T_var"), function(k) rng(na[, k]), ""), vapply(c("T_pop", "T_des", "T_var"), function(k) rng(pa[, k]), ""),
          vapply(c("T_pop", "T_des", "T_var"), function(k) sum(pa[, k] > max(na[, k])), 0L), R_A))
out <- c(out, "", sprintf("Registered run: %d null and %d positive-control replicates per network (bridge rb only), plus one scoring of the real cuts with both bridges; about %.2f CPU hours (%d replicates per network here; heavily loaded shared machine).",
  R_NULL, R_POS, (R_NULL + R_POS) * cpu_tot / 3600, R_P), "")
writeLines(out, "results/probes.md"); cat(out, sep = "\n")
